import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  root: { flex: 1 },
  body: { paddingBottom: 40 },
  topbar: {
    paddingVertical: 10,
    paddingLeft: 18,
    paddingRight: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  trainer: { flexDirection: 'row', alignItems: 'center', gap: 9 },
  avatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  initials: {
    color: '#ffffff',
    fontFamily: 'Inter_800ExtraBold',
    fontSize: 14,
    letterSpacing: 0.3,
  },
  trainerText: { fontSize: 14, lineHeight: 16.8 },
  iconButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    paddingTop: 2,
    paddingHorizontal: 18,
    paddingBottom: 12,
    fontFamily: 'Montserrat_800ExtraBold',
    fontSize: 27,
    lineHeight: 28.08,
    letterSpacing: -0.5,
  },
  page: { paddingHorizontal: 16 },
  empty: {
    paddingTop: 8,
    paddingHorizontal: 12,
    paddingBottom: 20,
    alignItems: 'center',
  },
  mascot: { width: 170, height: 170, marginBottom: 14 },
  glow: { position: 'absolute', width: 170, height: 182 },
  mascotImage: Platform.select({
    web: { filter: 'drop-shadow(0px 6px 10px rgba(90, 40, 10, 0.12))' },
    default: {
      shadowColor: '#5a280a',
      shadowOffset: { width: 0, height: 6 },
      shadowRadius: 10,
      shadowOpacity: 0.12,
    },
  }),
  emptyTitle: {
    fontFamily: 'Inter_700Bold',
    fontSize: 17,
    lineHeight: 23.8,
    textAlign: 'center',
  },
  emptyText: {
    fontFamily: 'Inter_400Regular',
    marginTop: 6,
    fontSize: 14,
    lineHeight: 21.7,
    textAlign: 'center',
  },
  visits: { marginTop: 24, paddingHorizontal: 16 },
  sectionTitle: {
    marginHorizontal: 4,
    marginBottom: 12,
    fontFamily: 'Inter_700Bold',
    fontSize: 16,
    lineHeight: 21.6,
  },
  visitsCard: { padding: 18 },
  week: { flexDirection: 'row', gap: 6 },
  column: { flex: 1, gap: 6, minWidth: 0 },
  weekday: {
    fontFamily: 'Inter_500Medium',
    fontSize: 14,
    lineHeight: 20.3,
    textAlign: 'center',
  },
  day: {
    aspectRatio: 1,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dayText: { fontFamily: 'Inter_600SemiBold', fontSize: 14, lineHeight: 20.3 },
  footnote: {
    fontFamily: 'Inter_400Regular',
    marginTop: 12,
    fontSize: 14,
    lineHeight: 21.7,
  },
  offline: {
    fontFamily: 'Inter_400Regular',
    marginVertical: 12,
    marginHorizontal: 16,
    padding: 12,
    borderRadius: 12,
    fontSize: 14,
    lineHeight: 20.3,
  },
  rowsCard: { padding: 6 },
  row: {
    paddingVertical: 14,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  rowMain: { flex: 1, minWidth: 0 },
  skeletonCircle: { width: 42, height: 42, borderRadius: 21 },
  skeletonTitle: { width: '60%', height: 14, borderRadius: 10 },
  skeletonMeta: { width: '40%', height: 12, borderRadius: 10, marginTop: 8 },
});
