const assert = require('node:assert/strict');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async () => {
  const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
  const page = await browser.newPage({ viewport: { width: 1200, height: 900 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(pathToFileURL(path.join(__dirname, 'index.html')).href);
  await page.locator('article.pose').last().waitFor();
  await page.waitForFunction(() => Array.from(document.images).every(img => img.complete));
  assert.equal(await page.locator('article.pose').count(), 9);
  assert.equal(await page.locator('.candidate').count(), 18);
  assert.deepEqual(await page.evaluate(() => Array.from(document.images).filter(img => !img.naturalWidth).map(img => img.src)), []);
  assert.equal(await page.evaluate(() => window.MASCOT_CANDIDATES.length), 9);
  await page.locator('#pause').click();
  assert.equal(await page.locator('.candidate[src$="poster.png"]').count(), 18);
  await page.locator('#replay').click();
  assert.equal(await page.locator('.candidate[src$="animation.webp"]').count(), 18);
  await page.locator('#reduce').check();
  assert.equal(await page.locator('.candidate[src$="poster.png"]').count(), 18);
  await page.locator('#reduce').uncheck();
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.waitForFunction(() => document.body.classList.contains('reduced'));
  assert.equal(await page.locator('.candidate[src$="poster.png"]').count(), 18);
  assert.equal(await page.locator('.panda__body').first().evaluate(el => getComputedStyle(el).animationName), 'none');
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  assert.deepEqual(errors, []);
  if (process.env.SCREENSHOT) await page.screenshot({ path: process.env.SCREENSHOT, fullPage: true });
  await browser.close();
  console.log('PASS: file://, 9 candidates, 36 images, pause/replay, user/system reduce motion, mobile layout, no runtime errors');
})().catch(error => { console.error(error); process.exitCode = 1; });
