import { StyleSheet } from 'react-native';
import { tokens } from '@/ui/theme';

export const createWorkoutStyles = (colors: typeof tokens.colors.light) =>
  StyleSheet.create({
    notes: {
      marginTop: 14,
      marginHorizontal: 16,
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderRadius: 16,
      backgroundColor: colors.workoutNotes,
      gap: 8,
    },
    noteRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'flex-start',
      gap: 10,
    },
    noteShare: {
      minHeight: 44,
      padding: 8,
      borderWidth: 1,
      borderColor: colors.workoutNoteBorder,
      borderRadius: 10,
      backgroundColor: colors.surface,
    },
    undo: { minHeight: 44, padding: 8 },
    pickerItem: {
      minHeight: 52,
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 12,
      gap: 2,
    },
    pickerInput: {
      minHeight: 52,
      paddingHorizontal: 14,
      borderRadius: 14,
      backgroundColor: colors.sunken,
      color: colors.ink,
      fontSize: 15,
      fontFamily: tokens.font.body,
      marginTop: 14,
    },
    menuItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      minHeight: 60,
      paddingVertical: 10,
      paddingHorizontal: 14,
      borderRadius: 16,
      backgroundColor: colors.sunken,
    },
    root: { flex: 1, backgroundColor: colors.canvas },
    row: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    grow: { flex: 1, minWidth: 0 },
    topbar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingTop: 10,
      paddingHorizontal: 8,
      paddingBottom: 2,
    },
    topSide: {
      width: 88,
      minHeight: 44,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 3,
    },
    icon: {
      width: 44,
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    topTitle: { fontSize: 14, lineHeight: 20.3, fontFamily: tokens.font.bold },
    small: { fontSize: 14, lineHeight: 20.3 },
    secondary: { color: colors.secondary },
    accent: { color: colors.workoutAccentInk },
    bold: { fontFamily: tokens.font.bold },
    head: { paddingTop: 2, paddingHorizontal: 18, paddingBottom: 14 },
    title: {
      fontFamily: tokens.font.heading,
      fontSize: 24,
      lineHeight: 27.6,
      letterSpacing: -0.6,
    },
    subtitle: {
      color: colors.secondary,
      fontSize: 14,
      lineHeight: 20.3,
      fontFamily: tokens.font.strong,
      marginTop: 6,
    },
    score: { fontFamily: tokens.font.heading, fontSize: 28, lineHeight: 30.2 },
    scoreTotal: {
      fontFamily: tokens.font.heading,
      fontSize: 16,
      lineHeight: 23.2,
      color: colors.secondary,
    },
    progress: {
      height: 8,
      borderRadius: 999,
      backgroundColor: colors.sunken,
      marginTop: 10,
      overflow: 'hidden',
    },
    progressFill: {
      height: 8,
      borderRadius: 999,
      backgroundColor: colors.accent,
    },
    body: { paddingTop: 12, paddingHorizontal: 16, gap: 16 },
    focus: {
      borderRadius: 28,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.workoutFocusBorder,
      paddingTop: 12,
      paddingBottom: 6,
      overflow: 'hidden',
      boxShadow: colors.workoutFocusShadow,
    },
    eyebrow: {
      paddingLeft: 16,
      paddingRight: 12,
      minHeight: 44,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
    },
    eyebrowText: {
      fontSize: 13,
      lineHeight: 18.85,
      letterSpacing: 0.65,
      textTransform: 'uppercase',
      color: colors.workoutAccentInk,
      fontFamily: tokens.font.bold,
    },
    next: {
      minHeight: 44,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 2,
      flexShrink: 1,
    },
    exerciseHead: {
      paddingTop: 2,
      paddingLeft: 18,
      paddingRight: 52,
      paddingBottom: 8,
    },
    exerciseName: {
      fontFamily: tokens.font.heading,
      fontSize: 20,
      lineHeight: 24,
      letterSpacing: -0.2,
    },
    exerciseGoal: {
      fontFamily: tokens.font.strong,
      color: colors.secondary,
      fontSize: 14,
      lineHeight: 20.3,
      marginTop: 3,
    },
    menu: {
      position: 'absolute',
      right: 6,
      top: 0,
      width: 44,
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
      opacity: 0.45,
    },
    chips: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
      marginHorizontal: 12,
      marginTop: 2,
      marginBottom: 8,
    },
    chip: {
      minHeight: 44,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingVertical: 6,
      paddingLeft: 6,
      paddingRight: 12,
      borderRadius: 999,
      backgroundColor: colors.sunken,
    },
    chipActive: {
      backgroundColor: colors.workoutAccentSoft,
      borderWidth: 1.5,
      borderColor: colors.accent,
    },
    chipNo: {
      width: 26,
      height: 26,
      borderRadius: 13,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    chipNoText: {
      fontSize: 13,
      lineHeight: 18.85,
      fontFamily: tokens.font.bold,
      color: colors.secondary,
    },
    chipNoActive: { backgroundColor: colors.accent },
    composer: {
      marginHorizontal: 12,
      marginTop: 4,
      marginBottom: 10,
      padding: 12,
      borderRadius: 20,
      backgroundColor: colors.sunken,
      gap: 10,
    },
    composerHead: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      minHeight: 51,
    },
    composerEdit: {
      padding: 6,
      gap: 2,
      minWidth: 44,
      minHeight: 44,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.surface,
      borderRadius: 12,
    },
    fields: { flexDirection: 'row', gap: 8 },
    field: {
      flex: 1,
      padding: 8,
      borderRadius: 16,
      backgroundColor: colors.surface,
      gap: 4,
    },
    fieldLabel: {
      textAlign: 'center',
      color: colors.secondary,
      fontFamily: tokens.font.strong,
      fontSize: 13,
      lineHeight: 18.85,
    },
    input: {
      padding: 0,
      height: 48,
      color: colors.ink,
      fontFamily: tokens.font.heading,
      fontSize: 32,
      lineHeight: 46.4,
      textAlign: 'center',
      borderRadius: 10,
    },
    step: {
      flex: 1,
      minHeight: 44,
      borderRadius: 12,
      backgroundColor: colors.sunken,
      alignItems: 'center',
      justifyContent: 'center',
    },
    foot: {
      paddingTop: 4,
      paddingHorizontal: 10,
      paddingBottom: 10,
      flexDirection: 'row',
      gap: 6,
    },
    addSet: {
      minHeight: 44,
      paddingHorizontal: 14,
      flexDirection: 'row',
      gap: 5,
      alignItems: 'center',
      borderRadius: 12,
      backgroundColor: colors.workoutAccentSoft,
    },
    list: { gap: 8 },
    listTitle: {
      fontSize: 16,
      lineHeight: 23.2,
      fontFamily: tokens.font.bold,
      marginHorizontal: 4,
    },
    listRows: {
      borderRadius: 20,
      overflow: 'hidden',
      backgroundColor: colors.surface,
    },
    exerciseRow: {
      paddingVertical: 10,
      paddingHorizontal: 14,
      gap: 12,
      flexDirection: 'row',
      alignItems: 'center',
      minHeight: 60,
      borderBottomWidth: 1,
      borderBottomColor: colors.workoutDivider,
    },
    exerciseActive: { backgroundColor: colors.workoutAccentSoft },
    mark: {
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: colors.sunken,
      alignItems: 'center',
      justifyContent: 'center',
    },
    markActive: { backgroundColor: colors.accent },
    addExercise: {
      minHeight: 44,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      opacity: 0.45,
    },
    footnote: {
      marginHorizontal: 22,
      marginVertical: 16,
      color: colors.secondary,
      fontSize: 13,
      lineHeight: 18.85,
    },
    dock: {
      paddingTop: 6,
      paddingHorizontal: 16,
      paddingBottom: 18,
      backgroundColor: colors.canvas,
    },
    feedback: { minHeight: 36, justifyContent: 'center' },
    voice: {
      flex: 1,
      minHeight: 62,
      borderRadius: 18,
      overflow: 'hidden',
      paddingVertical: 10,
      paddingLeft: 8,
      paddingRight: 16,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 9,
      opacity: 0.45,
    },
    voiceFace: {
      width: 42,
      height: 42,
      borderRadius: 14,
      backgroundColor: colors.workoutVoiceFace,
      alignItems: 'center',
      justifyContent: 'center',
    },
    finish: { minHeight: 62, paddingHorizontal: 16 },
    voiceMic: {
      position: 'absolute',
      right: -2,
      bottom: -2,
      width: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: colors.workoutVoiceBadge,
      alignItems: 'center',
      justifyContent: 'center',
    },
    error: { fontSize: 13, lineHeight: 18.85, color: colors.danger },
    complete: { padding: 18, gap: 12 },
    resultRow: {
      minHeight: 60,
      padding: 14,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      borderTopWidth: 1,
      borderTopColor: colors.workoutDivider,
    },
    participants: { paddingHorizontal: 16, paddingVertical: 8, gap: 8 },
    participant: {
      minWidth: 90,
      minHeight: 64,
      padding: 12,
      borderRadius: 18,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    participantActive: {
      borderColor: colors.accent,
      backgroundColor: colors.workoutAccentSoft,
    },
    context: { paddingHorizontal: 18, paddingBottom: 10 },
  });

export function getWorkoutStyles(
  fontScale: number,
  width: number,
  colors: typeof tokens.colors.light,
) {
  const workoutStyles = createWorkoutStyles(colors);
  if (fontScale <= 1.3 && width >= 360) return workoutStyles;
  return {
    ...workoutStyles,
    row: { ...workoutStyles.row, flexWrap: 'wrap' as const },
    topbar: { ...workoutStyles.topbar, flexWrap: 'wrap' as const, gap: 8 },
    topSide: { ...workoutStyles.topSide, width: undefined },
    topTitle: { ...workoutStyles.topTitle, flexShrink: 1 },
    eyebrow: { ...workoutStyles.eyebrow, flexWrap: 'wrap' as const },
    next: { ...workoutStyles.next, flexWrap: 'wrap' as const },
    chip: {
      ...workoutStyles.chip,
      maxWidth: '100%' as const,
      flexWrap: 'wrap' as const,
    },
    chipNo: {
      ...workoutStyles.chipNo,
      width: undefined,
      height: undefined,
      minWidth: 26,
      minHeight: 26,
      paddingHorizontal: 4,
    },
    mark: {
      ...workoutStyles.mark,
      width: undefined,
      height: undefined,
      minWidth: 30,
      minHeight: 30,
      paddingHorizontal: 4,
    },
    composerHead: {
      ...workoutStyles.composerHead,
      flexDirection: 'column' as const,
      alignItems: 'stretch' as const,
    },
    fields: { ...workoutStyles.fields, flexDirection: 'column' as const },
    field: { ...workoutStyles.field, flex: undefined },
    input: {
      ...workoutStyles.input,
      height: undefined,
      minHeight: 48 * fontScale,
    },
    foot: { ...workoutStyles.foot, flexWrap: 'wrap' as const },
    addSet: { ...workoutStyles.addSet, flexShrink: 1 },
    voice: { ...workoutStyles.voice, flex: undefined, width: '100%' as const },
    finish: { ...workoutStyles.finish, width: '100%' as const },
  };
}
