export const trainerInbox = {
  title: 'Входящие',
  seedTime: 'сегодня, 08:41',
  justNow: 'только что',
  back: 'Назад',
  active: 'Активные',
  history: 'История',
  clear: 'Всё согласовано',
  clearHint: 'Новых запросов на перенос нет.',
  client: 'Клиент',
  byTrainer: 'Запрос на перенос · предложено вами',
  byClient: 'Запрос на перенос · предложено клиентом',
  waitingTrainer: 'Ждёт вас',
  waitingClient: 'Ждёт клиента',
  current: 'Действует',
  proposed: 'Предложено',
  accept: 'Принять',
  counter: 'Другое время',
  decline: 'Отклонить',
  withdraw: 'Отозвать запрос',
  accepted: 'Перенос принят',
  declined: 'Отклонён',
  withdrawn: 'Отозван',
};
