import type { WorkoutExerciseSpec } from './types';

export const workoutExerciseLibrary: (WorkoutExerciseSpec & {
  aliases?: string[];
  group: string;
})[] = [
  {
    name: 'Приседания со штангой',
    bodyweight: false,
    unit: 'повт',
    aliases: [
      'присед',
      'приседы',
      'Приседания со штангой',
      'barbell full squat',
    ],
    group: 'Ноги · штанга',
  },
  {
    name: 'Румынская тяга',
    bodyweight: false,
    unit: 'повт',
    aliases: ['румынка', 'Румынская тяга', 'barbell romanian deadlift'],
    group: 'Ноги · штанга',
  },
  {
    name: 'Жим ногами',
    bodyweight: false,
    unit: 'повт',
    group: 'Ноги · тренажёр',
  },
  {
    name: 'Выпады с гантелями',
    bodyweight: false,
    unit: 'повт',
    aliases: ['Выпады с гантелями', 'dumbbell lunge'],
    group: 'Ноги · гантели',
  },
  {
    name: 'Болгарские выпады',
    bodyweight: false,
    unit: 'повт',
    group: 'Ноги · гантели',
  },
  {
    name: 'Ягодичный мост',
    bodyweight: false,
    unit: 'повт',
    group: 'Ноги · штанга',
  },
  {
    name: 'Становая тяга',
    bodyweight: false,
    unit: 'повт',
    aliases: ['становая', 'Становая тяга', 'barbell deadlift'],
    group: 'Спина · штанга',
  },
  {
    name: 'Тяга в наклоне',
    bodyweight: false,
    unit: 'повт',
    group: 'Спина · штанга',
  },
  {
    name: 'Тяга блока к поясу',
    bodyweight: false,
    unit: 'повт',
    aliases: ['Тяга нижнего блока сидя', 'cable low seated row'],
    group: 'Спина · блок',
  },
  {
    name: 'Тяга верхнего блока',
    bodyweight: false,
    unit: 'повт',
    aliases: ['верхний блок'],
    group: 'Спина · блок',
  },
  {
    name: 'Подтягивания',
    bodyweight: true,
    unit: 'повт',
    aliases: ['Подтягивания', 'pull-up'],
    group: 'Спина · вес тела',
  },
  {
    name: 'Гиперэкстензия',
    bodyweight: true,
    unit: 'повт',
    group: 'Спина · вес тела',
  },
  {
    name: 'Жим лёжа',
    bodyweight: false,
    unit: 'повт',
    aliases: ['Жим штанги лёжа', 'barbell bench press'],
    group: 'Грудь · штанга',
  },
  {
    name: 'Жим гантелей лёжа',
    bodyweight: false,
    unit: 'повт',
    group: 'Грудь · гантели',
  },
  {
    name: 'Жим гантелей под углом',
    bodyweight: false,
    unit: 'повт',
    group: 'Грудь · гантели',
  },
  {
    name: 'Отжимания',
    bodyweight: true,
    unit: 'повт',
    aliases: ['Отжимания', 'push-up'],
    group: 'Грудь · вес тела',
  },
  {
    name: 'Жим гантелей сидя',
    bodyweight: false,
    unit: 'повт',
    group: 'Плечи · гантели',
  },
  {
    name: 'Махи в стороны',
    bodyweight: false,
    unit: 'повт',
    aliases: [
      'разводка стоя',
      'Подъём гантелей в стороны',
      'dumbbell lateral raise',
    ],
    group: 'Плечи · гантели',
  },
  {
    name: 'Сгибания на бицепс с гантелями',
    bodyweight: false,
    unit: 'повт',
    aliases: [
      'бицуха',
      'бицепс',
      'Сгибание рук с гантелями',
      'dumbbell biceps curl',
    ],
    group: 'Руки · гантели',
  },
  {
    name: 'Разгибания на трицепс в блоке',
    bodyweight: false,
    unit: 'повт',
    group: 'Руки · блок',
  },
  {
    name: 'Планка',
    bodyweight: true,
    unit: 'сек',
    aliases: ['планочка'],
    group: 'Кор · вес тела',
  },
  {
    name: 'Скручивания',
    bodyweight: true,
    unit: 'повт',
    group: 'Кор · вес тела',
  },
  {
    name: 'Бёрпи',
    bodyweight: true,
    unit: 'повт',
    group: 'Кардио · вес тела',
  },
  {
    name: 'Гоблет-присед',
    bodyweight: false,
    unit: 'повт',
    group: 'Ноги',
  },
  {
    name: 'Фронтальные приседания',
    bodyweight: false,
    unit: 'повт',
    group: 'Ноги',
  },
  {
    name: 'Приседания в Смите',
    bodyweight: false,
    unit: 'повт',
    group: 'Ноги',
  },
  {
    name: 'Приседания сумо',
    bodyweight: false,
    unit: 'повт',
    group: 'Ноги',
  },
  {
    name: 'Выпады назад',
    bodyweight: false,
    unit: 'повт',
    group: 'Ноги',
  },
  {
    name: 'Зашагивания на платформу',
    bodyweight: false,
    unit: 'повт',
    group: 'Ноги',
  },
  {
    name: 'Разгибания ног в тренажёре',
    bodyweight: false,
    unit: 'повт',
    group: 'Ноги',
  },
  {
    name: 'Сгибания ног лёжа',
    bodyweight: false,
    unit: 'повт',
    group: 'Ноги',
  },
  {
    name: 'Сгибания ног сидя',
    bodyweight: false,
    unit: 'повт',
    group: 'Ноги',
  },
  {
    name: 'Отведение ноги в блоке',
    bodyweight: false,
    unit: 'повт',
    group: 'Ноги',
  },
  {
    name: 'Приведение ног в тренажёре',
    bodyweight: false,
    unit: 'повт',
    group: 'Ноги',
  },
  {
    name: 'Отведение ног в тренажёре',
    bodyweight: false,
    unit: 'повт',
    group: 'Ноги',
  },
  {
    name: 'Подъём на носки стоя',
    bodyweight: false,
    unit: 'повт',
    group: 'Ноги',
  },
  {
    name: 'Подъём на носки сидя',
    bodyweight: false,
    unit: 'повт',
    group: 'Ноги',
  },
  {
    name: 'Тяга гантели одной рукой',
    bodyweight: false,
    unit: 'повт',
    group: 'Спина',
  },
  {
    name: 'Тяга Т-грифа',
    bodyweight: false,
    unit: 'повт',
    group: 'Спина',
  },
  {
    name: 'Тяга с упором грудью',
    bodyweight: false,
    unit: 'повт',
    group: 'Спина',
  },
  {
    name: 'Пуловер в блоке',
    bodyweight: false,
    unit: 'повт',
    group: 'Спина',
  },
  {
    name: 'Тяга прямыми руками',
    bodyweight: false,
    unit: 'повт',
    group: 'Спина',
  },
  {
    name: 'Шраги с гантелями',
    bodyweight: false,
    unit: 'повт',
    group: 'Спина',
  },
  {
    name: 'Обратные подтягивания',
    bodyweight: true,
    unit: 'повт',
    group: 'Спина',
  },
  {
    name: 'Жим штанги под углом',
    bodyweight: false,
    unit: 'повт',
    group: 'Грудь',
  },
  {
    name: 'Сведение рук в кроссовере',
    bodyweight: false,
    unit: 'повт',
    group: 'Грудь',
  },
  {
    name: 'Разведение гантелей лёжа',
    bodyweight: false,
    unit: 'повт',
    group: 'Грудь',
  },
  {
    name: 'Жим в тренажёре',
    bodyweight: false,
    unit: 'повт',
    group: 'Грудь',
  },
  {
    name: 'Отжимания на брусьях',
    bodyweight: true,
    unit: 'повт',
    group: 'Грудь',
  },
  {
    name: 'Отжимания от скамьи',
    bodyweight: true,
    unit: 'повт',
    group: 'Грудь',
  },
  {
    name: 'Жим штанги стоя',
    bodyweight: false,
    unit: 'повт',
    group: 'Плечи',
  },
  {
    name: 'Жим Арнольда',
    bodyweight: false,
    unit: 'повт',
    group: 'Плечи',
  },
  {
    name: 'Махи в наклоне',
    bodyweight: false,
    unit: 'повт',
    group: 'Плечи',
  },
  {
    name: 'Подъём гантелей перед собой',
    bodyweight: false,
    unit: 'повт',
    group: 'Плечи',
  },
  {
    name: 'Тяга каната к лицу',
    bodyweight: false,
    unit: 'повт',
    group: 'Плечи',
  },
  {
    name: 'Обратная бабочка',
    bodyweight: false,
    unit: 'повт',
    group: 'Плечи',
  },
  {
    name: 'Сгибания со штангой',
    bodyweight: false,
    unit: 'повт',
    group: 'Руки',
  },
  {
    name: 'Молотковые сгибания',
    bodyweight: false,
    unit: 'повт',
    group: 'Руки',
  },
  {
    name: 'Сгибания на скамье Скотта',
    bodyweight: false,
    unit: 'повт',
    group: 'Руки',
  },
  {
    name: 'Сгибания в блоке',
    bodyweight: false,
    unit: 'повт',
    group: 'Руки',
  },
  {
    name: 'Французский жим',
    bodyweight: false,
    unit: 'повт',
    group: 'Руки',
  },
  {
    name: 'Разгибания рук из-за головы',
    bodyweight: false,
    unit: 'повт',
    group: 'Руки',
  },
  {
    name: 'Жим узким хватом',
    bodyweight: false,
    unit: 'повт',
    group: 'Руки',
  },
  {
    name: 'Боковая планка',
    bodyweight: true,
    unit: 'сек',
    group: 'Кор',
  },
  {
    name: 'Обратные скручивания',
    bodyweight: true,
    unit: 'повт',
    group: 'Кор',
  },
  {
    name: 'Подъём коленей в висе',
    bodyweight: true,
    unit: 'повт',
    group: 'Кор',
  },
  {
    name: 'Мёртвый жук',
    bodyweight: true,
    unit: 'повт',
    group: 'Кор',
  },
  {
    name: 'Скручивания в блоке',
    bodyweight: false,
    unit: 'повт',
    aliases: ['Скручивания на верхнем блоке', 'cable kneeling crunch'],
    group: 'Кор',
  },
  {
    name: 'Паллоф-пресс',
    bodyweight: false,
    unit: 'повт',
    group: 'Кор',
  },
  {
    name: 'Ходьба на дорожке',
    bodyweight: true,
    unit: 'сек',
    group: 'Кардио',
  },
  {
    name: 'Бег на дорожке',
    bodyweight: true,
    unit: 'сек',
    group: 'Кардио',
  },
  {
    name: 'Велотренажёр',
    bodyweight: true,
    unit: 'сек',
    group: 'Кардио',
  },
  {
    name: 'Гребной тренажёр',
    bodyweight: true,
    unit: 'сек',
    group: 'Кардио',
  },
  {
    name: 'Скакалка',
    bodyweight: true,
    unit: 'сек',
    group: 'Кардио',
  },
  {
    name: 'Кошка-корова',
    bodyweight: true,
    unit: 'сек',
    group: 'Мобильность',
  },
  {
    name: 'Повороты грудного отдела',
    bodyweight: true,
    unit: 'сек',
    group: 'Мобильность',
  },
  {
    name: 'Растяжка сгибателей бедра',
    bodyweight: true,
    unit: 'сек',
    group: 'Мобильность',
  },
  {
    name: 'Мобилизация голеностопа',
    bodyweight: true,
    unit: 'сек',
    group: 'Мобильность',
  },
  {
    name: 'Круги плечами',
    bodyweight: true,
    unit: 'сек',
    group: 'Мобильность',
  },
  {
    name: 'Глубокий присед с опорой',
    bodyweight: true,
    unit: 'сек',
    group: 'Мобильность',
  },
  {
    name: 'Тяга верхнего блока параллельным хватом',
    bodyweight: false,
    unit: 'повт',
    aliases: [
      'Тяга верхнего блока параллельным хватом',
      'twin handle parallel grip lat pulldown',
    ],
    group: 'Спина · блок',
  },
];

export const workoutExerciseKey = (name: string) =>
  name
    .toLowerCase()
    .replace(/ё/g, 'е')
    .replace(/[-‐‑–—]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
