export const workoutDemo = {
  rest: 'Отдых',
  restDone: 'Отдых окончен',
  restTime: ' {{time}}',
  restLess: 'Отдых на 15 секунд меньше',
  restMore: 'Отдых на 15 секунд больше',
  minus15: '−15',
  plus15: '+15',
  hideRest: 'Скрыть',
  skipRest: 'Хватит',
  nextExercise: 'дальше {{name}}',
  resume: 'Вернуться',
  resumeLabel: 'Вернуться к тренировке: {{name}}, {{start}}. {{detail}}',
  saveError: 'Ошибка сохранения · вернитесь к журналу',
  participant: 'Участник',
  groupName: '{{title}} · {{name}}',
  groupDrafts: 'Черновики: {{participants}} участн.',
  draft: 'Есть черновик',
  notParticipating: 'Участник не участвует',
  noProgram: 'Без программы',
  progress: '{{done}} из {{total}} подходов',
  count: '{{done}}/{{total}}',
  join: '{{first}} · {{second}}',
  current: '{{detail}}. Сейчас: {{exercise}}',
} as const;
