import { StyleSheet } from 'react-native';
import { tokens } from '@/ui/theme';

export const scheduleStyles = StyleSheet.create({
  root: { flex: 1 },
  header: {
    paddingTop: 10,
    paddingHorizontal: 22,
    paddingBottom: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  title: {
    fontFamily: tokens.font.heading,
    fontSize: 27,
    lineHeight: 32.4,
    letterSpacing: -0.8,
  },
  iconButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9999,
  },
  body: { paddingBottom: 100 },
  nav: {
    marginHorizontal: 16,
    paddingTop: 14,
    paddingHorizontal: 10,
    paddingBottom: 12,
    boxShadow: 'none',
  },
  row: { flexDirection: 'row', alignItems: 'center' },
  month: { paddingHorizontal: 6, justifyContent: 'space-between', gap: 8 },
  monthTitle: {
    fontFamily: tokens.font.displayBold,
    fontSize: 17,
    lineHeight: 22.1,
    letterSpacing: -0.4,
  },
  today: {
    minHeight: 44,
    paddingHorizontal: 12,
    borderRadius: 9999,
    justifyContent: 'center',
  },
  small: { fontSize: 14, lineHeight: 20.3 },
  medium: { fontFamily: tokens.font.medium },
  strong: { fontFamily: tokens.font.strong },
  bold: { fontFamily: tokens.font.bold },
  weekNav: { justifyContent: 'space-between', marginVertical: 4 },
  week: { flexDirection: 'row', gap: 2 },
  day: {
    flex: 1,
    minWidth: 44,
    minHeight: 92,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    borderRadius: 9999,
  },
  dayNumber: {
    fontFamily: tokens.font.displayBold,
    fontSize: 19,
    lineHeight: 22.8,
  },
  underline: { textDecorationLine: 'underline' },
  key: {
    justifyContent: 'space-between',
    gap: 8,
    paddingHorizontal: 6,
    paddingTop: 13,
  },
  section: { paddingTop: 22, paddingHorizontal: 16, paddingBottom: 26 },
  dayHeading: { paddingHorizontal: 6, paddingBottom: 15 },
  dayTitle: {
    fontFamily: tokens.font.displayBold,
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: -0.4,
  },
  subtitle: { marginTop: 3 },
  agenda: { paddingHorizontal: 12, boxShadow: 'none' },
  entry: {
    paddingVertical: 18,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  divider: { borderTopWidth: 1 },
  time: { width: 48, gap: 4 },
  main: { flex: 1, minWidth: 0 },
  content: { flex: 1, minWidth: 0, gap: 4 },
  name: { fontFamily: tokens.font.bold, fontSize: 15, lineHeight: 20.25 },
  detail: { fontSize: 14, lineHeight: 21 },
  confirmed: { gap: 4 },
  chevron: { marginTop: 4 },
  gap: {
    paddingVertical: 12,
    paddingLeft: 60,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderStyle: 'dashed',
    gap: 8,
  },
  gapLabels: { flex: 1, gap: 3 },
  overlap: {
    marginVertical: 8,
    marginHorizontal: -5,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderRadius: 18,
  },
  overlapLabel: { gap: 6, paddingVertical: 10, borderBottomWidth: 1 },
  request: {
    marginTop: -4,
    marginLeft: 60,
    marginBottom: 14,
    padding: 10,
    borderRadius: 14,
    gap: 8,
  },
  requestDate: { marginTop: 4 },
  notice: {
    paddingVertical: 13,
    paddingHorizontal: 15,
    borderRadius: 18,
    gap: 11,
    marginBottom: 12,
    alignItems: 'flex-start',
  },
  empty: {
    paddingVertical: 30,
    paddingHorizontal: 20,
    alignItems: 'center',
    gap: 4,
    boxShadow: 'none',
  },
  emptyArt: {
    width: 190,
    height: 140,
    marginBottom: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pandaBox: {
    width: 170,
    height: 170,
    marginBottom: 14,
    flexShrink: 0,
    justifyContent: 'flex-end',
  },
  pandaImage: { height: (170 * 148) / 227 },
  emptyTitle: {
    fontFamily: tokens.font.heading,
    fontSize: 19,
    lineHeight: 27.55,
    letterSpacing: -0.3,
    textAlign: 'center',
  },
  emptyHint: {
    fontFamily: tokens.font.medium,
    fontSize: 14,
    lineHeight: 21,
    maxWidth: 270,
    marginTop: 6,
    textAlign: 'center',
  },
  emptyAction: { marginTop: 20, width: '100%', maxWidth: 280 },
  skeletonCard: { padding: 6 },
  skeletonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingVertical: 14,
    paddingHorizontal: 12,
  },
  skeletonAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    overflow: 'hidden',
  },
  skeletonLine: {
    width: '60%',
    height: 14,
    borderRadius: 10,
    overflow: 'hidden',
  },
  skeletonSubline: {
    width: '40%',
    height: 12,
    marginTop: 8,
    borderRadius: 10,
    overflow: 'hidden',
  },
});
