export const trainerSchedule = {
  title: 'Расписание',
  add: 'Добавить занятие',
  addDay: 'Добавить занятие на выбранный день',
  today: 'Сегодня',
  previousWeek: 'Предыдущая неделя',
  nextWeek: 'Следующая неделя',
  dateSelection: 'Выбор даты',
  selectedDay: 'Занятия выбранного дня',
  countKey: 'Количество занятий под датой',
  city: 'Алматы',
  loading: 'Загружаем расписание…',
  offline: 'Нет связи. Показано сохранённое расписание.',
  empty: 'День свободен',
  emptyHint: 'Запланируйте занятие — выбранная дата уже будет заполнена.',
  sessions_one: '{{count}} занятие',
  sessions_few: '{{count}} занятия',
  sessions_many: '{{count}} занятий',
  sessions_other: '{{count}} занятия',
  total: '{{sessions}} · {{duration}} занятий',
  hours: '{{count}} ч',
  minutes: '{{count}} мин',
  hoursMinutes: '{{hours}} ч {{minutes}} мин',
  free: 'Свободно · {{duration}}',
  overlap: 'Пересечение · {{sessions}}',
  confirmed: 'Подтверждено',
  groupConfirmed: 'Общее занятие',
  journal: 'Журнал в работе',
  noProgram: 'Программа пока не назначена',
  request: 'Перенос · нужен ваш ответ',
  proposed: 'Предложено {{date}}, {{time}}',
  open: '{{name}}, {{start}}–{{end}}. Открыть занятие',
  unavailable: 'Этот сценарий ещё не подключён',
  groupSummary: '1 подтвердил · 1 ждёт · 1 отменил',
  groupNames: 'Алия, Мади, Дана',
  people: {
    dana: 'Дана',
    madi: 'Мади',
    arman: 'Арман',
    aigerim: 'Айгерим',
    group: 'Мини-группа',
  },
  programs: {
    fullBody: 'Full Body',
    upper: 'Верх Б',
    strength: 'Сила 5×5',
    lower: 'Низ А',
  },
  weekdays: ['пн', 'вт', 'ср', 'чт', 'пт', 'сб', 'вс'],
  monthsShort: [
    'янв',
    'фев',
    'мар',
    'апр',
    'мая',
    'июн',
    'июл',
    'авг',
    'сен',
    'окт',
    'ноя',
    'дек',
  ],
};
