import { StyleSheet } from 'react-native';
import { tokens } from '@/ui/theme';

export const todayStyles = StyleSheet.create({
  root: { flex: 1 },
  body: { paddingBottom: 100 },
  actions: { flexDirection: 'row', gap: 8 },
  action: {
    width: 44,
    height: 44,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    overflow: 'visible',
  },
  badge: {
    position: 'absolute',
    right: -4,
    top: -4,
    minWidth: 19,
    height: 19,
    paddingHorizontal: 5,
    borderRadius: 9999,
    backgroundColor: '#ffb23d',
    color: '#2a1a05',
    fontFamily: tokens.font.extraBold,
    fontSize: 14,
    lineHeight: 20.3,
    textAlign: 'center',
  },
  buddy: {
    marginHorizontal: 16,
    marginTop: 4,
    marginBottom: 18,
    paddingTop: 16,
    paddingBottom: 16,
    paddingLeft: 12,
    paddingRight: 16,
    borderRadius: 24,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    overflow: 'hidden',
    boxShadow: '0px 18px 36px -18px rgba(242,242,243,0.7)',
  },
  buddyGlowTop: {
    position: 'absolute',
    width: 180,
    height: 180,
    right: -60,
    top: -80,
  },
  buddyGlowBottom: {
    position: 'absolute',
    width: 120,
    height: 120,
    left: -40,
    bottom: -70,
  },
  face: {
    width: 64,
    height: 64,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  faceImage: { width: 56, height: 49 },
  main: { flex: 1, minWidth: 0 },
  buddyLine: {
    fontFamily: tokens.font.bold,
    fontSize: 15,
    lineHeight: 20.25,
    letterSpacing: -0.1,
    color: '#f2f2f3',
  },
  bar: {
    marginTop: 10,
    height: 8,
    borderRadius: 99,
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.14)',
  },
  progress: { width: '71%', height: 8, borderRadius: 99, overflow: 'hidden' },
  stats: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    columnGap: 14,
    rowGap: 6,
    marginTop: 9,
  },
  stat: { fontSize: 14, lineHeight: 20.3, color: 'rgba(255,248,240,0.8)' },
  statNumber: { fontFamily: tokens.font.extraBold, color: '#ffffff' },
  requests: {
    minHeight: 44,
    paddingHorizontal: 8,
    borderRadius: 99,
    justifyContent: 'center',
    backgroundColor: '#ffb23d',
  },
  requestText: {
    color: '#2a1a05',
    fontSize: 14,
    lineHeight: 20.3,
    fontFamily: tokens.font.bold,
  },
  section: { paddingTop: 2, paddingHorizontal: 16, paddingBottom: 26 },
  sectionHead: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 6,
    paddingBottom: 12,
    gap: 10,
  },
  small: { fontSize: 14, lineHeight: 20.3 },
  strong: { fontFamily: tokens.font.strong },
  agenda: { borderRadius: 28, overflow: 'hidden', borderWidth: 1 },
  past: { marginBottom: 4 },
  toggle: {
    minHeight: 52,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  pastLabel: {
    flex: 1,
    fontFamily: tokens.font.strong,
    fontSize: 15,
    lineHeight: 19.5,
  },
  entry: { paddingVertical: 16, paddingHorizontal: 18, borderTopWidth: 1 },
  caption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 13,
  },
  row: { flexDirection: 'row', gap: 14 },
  time: { width: 72, paddingTop: 2 },
  timeText: {
    fontFamily: tokens.font.heading,
    fontSize: 18,
    lineHeight: 23.4,
    letterSpacing: -0.4,
  },
  timeExpanded: { fontSize: 23, lineHeight: 29.9, letterSpacing: -0.8 },
  endTime: {
    marginTop: 5,
    fontFamily: tokens.font.medium,
    fontSize: 14,
    lineHeight: 20.3,
  },
  name: {
    fontFamily: tokens.font.heading,
    fontSize: 20,
    lineHeight: 25,
    letterSpacing: -0.4,
  },
  nameButton: {
    minHeight: 44,
    marginTop: -6,
    marginBottom: -4,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  compactName: { fontFamily: tokens.font.bold, fontSize: 16, lineHeight: 23.2 },
  program: {
    marginTop: 6,
    flexDirection: 'row',
    flexWrap: 'wrap',
    columnGap: 8,
    rowGap: 3,
  },
  programText: { fontSize: 14, lineHeight: 21 },
  programPicker: {
    minHeight: 44,
    marginVertical: -12,
    justifyContent: 'center',
  },
  rsvp: {
    minHeight: 44,
    marginTop: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  rsvpItems: { flexDirection: 'row', gap: 12 },
  rsvpItem: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  cta: { marginTop: 8, opacity: 1 },
  activeStripe: {
    position: 'absolute',
    top: 16,
    height: 40,
    left: 0,
    width: 4,
    borderRadius: 4,
  },
  gap: {
    minHeight: 72,
    borderTopWidth: 1,
    paddingVertical: 13,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  gapTime: {
    fontSize: 14,
    lineHeight: 20.3,
    fontFamily: tokens.font.displayBold,
  },
  dayEnd: {
    paddingTop: 14,
    paddingHorizontal: 6,
    fontFamily: tokens.font.medium,
    fontSize: 14,
    lineHeight: 20.3,
  },
  notice: {
    marginHorizontal: 16,
    marginBottom: 12,
    paddingVertical: 13,
    paddingHorizontal: 15,
    borderRadius: 18,
    flexDirection: 'row',
    gap: 11,
  },
  noticeText: {
    flex: 1,
    fontSize: 14,
    lineHeight: 21,
    fontFamily: tokens.font.medium,
  },
  empty: {
    marginHorizontal: 16,
    marginTop: 4,
    marginBottom: 24,
    paddingVertical: 52,
    paddingHorizontal: 48,
    gap: 4,
    borderWidth: 1,
    borderRadius: 24,
    alignItems: 'center',
  },
  emptyArtBox: {
    width: 190,
    height: 140,
    marginBottom: 18,
    alignItems: 'center',
  },
  emptyArt: { width: 170, height: 170, marginBottom: 14 },
  emptyTitle: {
    fontFamily: tokens.font.heading,
    fontSize: 19,
    lineHeight: 27.55,
    letterSpacing: -0.3,
    textAlign: 'center',
  },
  emptyDescription: {
    fontSize: 14,
    lineHeight: 21,
    textAlign: 'center',
    marginTop: 6,
  },
  emptyButton: { marginTop: 20, maxWidth: 280, opacity: 1, width: '100%' },
  gapBorder: {
    position: 'absolute',
    top: 7,
    bottom: 7,
    left: 10,
    right: 10,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderRadius: 18,
  },
  skeletonHead: {
    paddingTop: 10,
    paddingHorizontal: 22,
    paddingBottom: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  skeletonTitle: { width: 120, height: 24, borderRadius: 8 },
  skeletonSubtitle: { width: 150, height: 12, marginTop: 10, borderRadius: 8 },
  skeletonAction: { width: 44, height: 44, borderRadius: 14 },
  skeletonLabel: {
    width: 92,
    height: 12,
    borderRadius: 8,
    marginLeft: 22,
    marginTop: 2,
    marginBottom: 12,
  },
  skeletonCard: { height: 280, borderRadius: 26, marginHorizontal: 16 },
});
