export const trainerToday = {
  journalStatusFailed:
    'Не удалось загрузить статусы журналов. Показаны последние загруженные данные.',
  until: 'до {{time}}',
  resumeJournal: 'Продолжить журнал',
  consentPending: 'Ждём согласия',
  clientReplyPending: 'Ждём ответа клиента',
  noPast: 'Прошедших занятий нет',
  cancellations_one: ' · {{count}} отмена',
  cancellations_few: ' · {{count}} отмены',
  cancellations_many: ' · {{count}} отмен',
  cancellations_other: ' · {{count}} отмены',
  groupConfirmed_one: '{{count}} подтвердил',
  groupConfirmed_few: '{{count}} подтвердили',
  groupConfirmed_many: '{{count}} подтвердили',
  groupConfirmed_other: '{{count}} подтвердили',
  groupWaiting_one: '{{count}} ждёт',
  groupWaiting_few: '{{count}} ждут',
  groupWaiting_many: '{{count}} ждут',
  groupWaiting_other: '{{count}} ждут',
  groupCancelled_one: '{{count}} отменил',
  groupCancelled_few: '{{count}} отменили',
  groupCancelled_many: '{{count}} отменили',
  groupCancelled_other: '{{count}} отменили',
  programPreview: '{{name}} · {{exercises}}{{more}}',
  moreExercises: ' · ещё {{count}}',
  calmNow: 'Сейчас · ещё {{duration}}',
  calmNext: 'Следующее · через {{duration}}',
  further: 'Дальше',
  replyNeeded: 'Нужен ответ',
  reply: 'Ответить',
  moveKind: 'перенос',
  freeAfter: 'Дальше свободно',
  durationMinutes: '{{count}} мин',
  participantWaiting: ' · ждёт',
  participantConfirmed: 'подтвердил',
  participantCancelled: 'отменил',
  inboxEmpty: 'Входящие: нет запросов, требующих ответа',
  allPast: 'Все занятия на сегодня позади',
  cancelled: 'Отменено',
  overlapDuration: 'Пересечение · {{duration}}',
  title: 'Сегодня',
  date: 'пн, 14 сен',
  sessionTime: '{{date}} · {{time}}',
  inboxDynamic_one: 'Входящие: {{count}} запрос требует ответа',
  inboxDynamic_few: 'Входящие: {{count}} запроса требуют ответа',
  inboxDynamic_many: 'Входящие: {{count}} запросов требуют ответа',
  inboxDynamic_other: 'Входящие: {{count}} запроса требуют ответа',
  create: 'Создать занятие',
  pastCount_one: 'Прошло {{count}} занятие',
  pastCount_few: 'Прошло {{count}} занятия',
  pastCount_many: 'Прошло {{count}} занятий',
  pastCount_other: 'Прошло {{count}} занятия',
  show: 'Показать',
  hide: 'Скрыть',
  miniGroup: 'Мини-группа',
  start: 'Начать тренировку',
  resume: 'Продолжить тренировку',
  results: 'Посмотреть результаты',
  journalDraft: 'Журнал в работе',
  journalFinished: 'Журнал завершён',
  add: 'Добавить занятие',
  noProgram: 'Без программы',
  emptyTitle: 'Сегодня занятий нет',
  emptyDescription: 'Добавьте занятие — клиент получит предложение времени.',
  offline:
    'Нет связи. Показано из последней загрузки, изменения могут быть не отправлены.',
  sessionLabel: 'Занятие {{name}}, {{start}}–{{end}}',
  attendance: 'Посещение и списание',
  unmarked: 'Пока не отмечено',
  present: 'Пришёл',
  absent: 'Не пришёл',
  move: 'Перенести занятие',
  cancel: 'Отменить запись',
  attendanceHelp:
    'Отмена не списывает занятие. Списание за отмену или неявку оформляется отдельно, с причиной.',
  people: {
    dana: 'Дана',
    danaFull: 'Дана Ержанова',
    madi: 'Мади',
    madiFull: 'Мади Касымов',
    arman: 'Арман',
    armanFull: 'Арман Оспанов',
    aigerim: 'Айгерим',
    aigerimFull: 'Айгерим Бекова',
    aliya: 'Алия',
    aliyaFull: 'Алия Нурлановa',
  },
  sessionTitles: {
    morning: 'Утренняя сессия',
    personal: 'Индивидуальная',
    stretch: 'Растяжка',
  },
};
