export const trainerToday = {
  greeting: 'Добрый вечер, Данияр',
  greetingNight: 'Доброй ночи, {{name}}',
  greetingMorning: 'Доброе утро, {{name}}',
  greetingDay: 'Добрый день, {{name}}',
  greetingEvening: 'Добрый вечер, {{name}}',
  nextSession: 'Следующая тренировка',
  requestReply: 'Перенос · ответить',
  cancelled: 'Отменено',
  participantsDynamic:
    'Участники мини-группы: {{confirmed}} подтвердили · {{pending}} ждут · {{cancelled}} отменили',
  overlapLabel:
    'Пересечение: {{start}}–{{end}}, {{minutes}} минут. Сведения о конфликтующих записях',
  overlapDuration: 'Пересечение · {{duration}}',
  overlapTime: '{{start}}–{{end}} · отдельные занятия',
  title: 'Сегодня',
  date: 'пн, 14 сен',
  clock: '20:30',
  freeStart: '21:00',
  sessionTime: '{{date}} · {{time}}',
  inbox: 'Входящие: 2 запроса требуют ответа',
  inboxDynamic_one: 'Входящие: {{count}} запрос требует ответа',
  inboxDynamic_few: 'Входящие: {{count}} запроса требуют ответа',
  inboxDynamic_many: 'Входящие: {{count}} запросов требуют ответа',
  inboxDynamic_other: 'Входящие: {{count}} запроса требуют ответа',
  create: 'Создать занятие',
  summary: 'Сводка дня',
  freeMinutes: 'Свободно · {{count}} мин',
  pastCount_one: 'Прошло {{count}} занятие',
  pastCount_few: 'Прошло {{count}} занятия',
  pastCount_many: 'Прошло {{count}} занятий',
  pastCount_other: 'Прошло {{count}} занятия',
  requestsCount_one: '{{count}} запрос',
  requestsCount_few: '{{count}} запроса',
  requestsCount_many: '{{count}} запросов',
  requestsCount_other: '{{count}} запроса',
  ongoingCount_one: 'Сейчас идёт {{count}} занятие.',
  ongoingCount_few: 'Сейчас идёт {{count}} занятия.',
  ongoingCount_many: 'Сейчас идёт {{count}} занятий.',
  ongoingCount_other: 'Сейчас идёт {{count}} занятия.',
  aheadCount_one: 'Впереди {{count}} занятие. Разминаемся!',
  aheadCount_few: 'Впереди {{count}} занятия. Разминаемся!',
  aheadCount_many: 'Впереди {{count}} занятий. Разминаемся!',
  aheadCount_other: 'Впереди {{count}} занятия. Разминаемся!',
  leftCount_one: 'Осталось {{count}} занятие — вы в ритме.',
  leftCount_few: 'Осталось {{count}} занятия — вы в ритме.',
  leftCount_many: 'Осталось {{count}} занятий — вы в ритме.',
  leftCount_other: 'Осталось {{count}} занятия — вы в ритме.',
  done: 'Все занятия позади. Отличная работа!',
  progressCount: 'По времени завершилось {{done}} из {{total}}',
  endTime: 'Последнее занятие до {{time}}',

  ongoing: 'Сейчас идёт 1 занятие.',
  progress: 'По времени завершилось 5 из 7',
  behind: 'позади',
  ahead: 'впереди',
  now: 'сейчас',
  requests: '2 запроса',
  plan: 'План дня',
  count: '7 занятий',
  past: 'Прошло 5 занятий',
  show: 'Показать',
  hide: 'Скрыть',
  happening: 'Идёт сейчас',
  until: 'до {{time}}',
  miniGroup: 'Мини-группа',
  groupNames: 'Алия, Мади, Дана',
  participants: 'Участники мини-группы: 1 подтвердил · 1 ждёт · 1 отменил',
  start: 'Начать тренировку',
  resume: 'Продолжить тренировку',
  results: 'Посмотреть результаты',
  openJournal: 'Открыть журнал · {{name}}',
  journalDraft: 'Журнал в работе',
  journalFinished: 'Журнал завершён',
  free: 'Свободно · 15 мин',
  add: 'Добавить занятие',
  personal: 'Индивидуальное',
  noProgram: 'Без программы',
  chooseProgram: 'Выбрать программу',
  end: 'Последнее занятие до 22:00',
  elapsed: 'время прошло',
  emptyTitle: 'Сегодня занятий нет',
  emptyDescription: 'Добавьте занятие — клиент получит предложение времени.',
  offline:
    'Нет связи. Показано из последней загрузки, изменения могут быть не отправлены.',
  sessionLabel: 'Занятие {{name}}, {{start}}–{{end}}',
  attendance: 'Посещение и списание',
  unmarked: 'Пока не отмечено',
  present: 'Пришёл',
  absent: 'Не пришёл',
  move: 'Перенести занятие',
  cancel: 'Отменить запись',
  attendanceHelp:
    'Отмена не списывает занятие. Списание за отмену или неявку оформляется отдельно, с причиной.',
  people: {
    dana: 'Дана',
    danaFull: 'Дана Ержанова',
    madi: 'Мади',
    madiFull: 'Мади Касымов',
    arman: 'Арман',
    armanFull: 'Арман Оспанов',
    aigerim: 'Айгерим',
    aigerimFull: 'Айгерим Бекова',
    aliya: 'Алия',
    aliyaFull: 'Алия Нурлановa',
  },
  programs: {
    fullBody:
      'Full Body · Приседания со штангой, Отжимания, Тяга в наклоне · ещё 1',
    upper:
      'Верх Б · Жим лёжа, Жим гантелей под углом, Тяга блока к поясу · ещё 1',
    strength: 'Сила 5×5 · Приседания со штангой, Жим лёжа, Становая тяга',
    lower: 'Низ А · Приседания со штангой, Румынская тяга, Жим ногами · ещё 2',
  },
  sessionTitles: {
    morning: 'Утренняя сессия',
    personal: 'Индивидуальная',
    stretch: 'Растяжка',
  },
};
