// Real prototype, fresh contexts, UI actions only. No fixture / Store writes.
const {chromium}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const out=__dirname, origin='http://127.0.0.1:4188';
const sha=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');
(async()=>{const browser=await chromium.launch();const report={browser:browser.version(),captured_at:new Date().toISOString(),url:origin+'/prototype/?now=08:00',viewport:{width:375,height:844},deviceScaleFactor:1,screens:[],errors:[]};
async function fresh(){const ctx=await browser.newContext({viewport:report.viewport,deviceScaleFactor:1,isMobile:true,hasTouch:true,locale:'ru-RU',timezoneId:'Asia/Almaty',reducedMotion:'reduce'});const p=await ctx.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(report.url);await p.getByRole('heading',{name:'Сегодня',exact:true,level:1}).waitFor();await p.evaluate(()=>document.fonts.ready);return p;}
async function capture(p,name){await p.waitForFunction(()=>!document.querySelector('.toast.is-on'));await p.evaluate(async()=>{await document.fonts.ready;await new Promise(requestAnimationFrame);await new Promise(requestAnimationFrame);});const file=path.join(out,'screens/base',name+'.png');await p.screenshot({path:file,animations:'disabled'});const elements=await p.locator('#screen').evaluate(el=>({text:el.innerText,nodes:[...el.querySelectorAll('button,.card,.row,.setrow,.log-context,.chip,h1,h2,h3,p,.num')].map(n=>({tag:n.tagName,cls:n.className,text:n.innerText,rect:{x:n.getBoundingClientRect().x,y:n.getBoundingClientRect().y,w:n.getBoundingClientRect().width,h:n.getBoundingClientRect().height}}))}));report.screens.push({name,file:path.relative(out,file),sha256:sha(file),...elements});console.log(name, elements.text);}
try{const p=await fresh();await capture(p,'today');await p.getByRole('button',{name:'Начать тренировку',exact:true}).click();for(const [i,kg,reps]of[[0,'50','10'],[1,'52,5','10']]){await p.locator(`.session-journal [data-id="setlog"][data-ex="e1"][data-si="${i}"]`).click();await p.getByLabel('Вес, кг',{exact:true}).fill(kg);await p.getByLabel('Повторы',{exact:true}).fill(reps);await p.getByRole('button',{name:'Записать подход',exact:true}).click();}await p.locator('.session-journal .screen__body').evaluate(e=>e.scrollTop=0);await capture(p,'journal');await p.context().close();
const x=await fresh();await x.getByText('Добавить занятие',{exact:true}).first().click();const close=x.getByRole('button',{name:'Закрыть',exact:true});await close.screenshot({path:path.join(out,'sizes/system-close.png')});report.close=await close.evaluate(e=>({html:e.outerHTML,svg:e.querySelector('svg')?.outerHTML,width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height,color:getComputedStyle(e).color,background:getComputedStyle(e).backgroundColor}));if(!report.close.svg)throw Error('Expected actual close SVG');fs.writeFileSync(path.join(out,'logos/system-close.svg'),report.close.svg.replace('<svg ','<svg xmlns="http://www.w3.org/2000/svg" '));await x.context().close();
const c=await fresh();await c.locator('.tabbar').getByRole('button',{name:'Клиенты',exact:true}).click();await c.locator('[data-act="client.open"]').first().click();await c.getByRole('button',{name:'Прогресс',exact:true}).click();await capture(c,'client-progress');await c.getByRole('button',{name:'Оплаты',exact:true}).click();await c.getByRole('button',{name:'Оплаты',exact:true}).evaluate(e=>e.scrollIntoView({block:'nearest',inline:'center'}));await capture(c,'client-package');await c.context().close();
fs.writeFileSync(path.join(out,'evidence/capture.json'),JSON.stringify(report,null,2));if(report.errors.length)throw Error(report.errors.join('\n'));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
