const { chromium, expect } = require('@playwright/test');
const assert = require('node:assert/strict');
require('node:fs').mkdirSync('output/library-review', {recursive:true});
(async () => {
 const browser=await chromium.launch({headless:true});
 try {
  const context=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});
  const p=await context.newPage(); const errors=[];
  p.on('pageerror', e=>errors.push(e.message));
  await p.goto((process.env.LIBRARY_TEST_URL || 'http://127.0.0.1:8788/prototype-fresh/'));
  await p.getByRole('button',{name:'Библиотека',exact:true}).click();
  await expect(p.getByRole('heading',{name:'Библиотека',exact:true})).toBeVisible();
  await p.screenshot({path:'output/library-review/exercises-mobile.png'});
  await p.getByRole('searchbox',{name:'Поиск упражнений',exact:true}).fill('bench');
  await expect(p.locator('.lib-exercises li')).toHaveCount(1);
  await p.getByRole('button',{name:'В избранное: Жим лёжа',exact:true}).click();
  await p.getByRole('searchbox',{name:'Поиск упражнений',exact:true}).fill('');
  await p.getByRole('button',{name:'Избранное',exact:true}).click();
  await expect(p.locator('.lib-exercises li')).toHaveCount(1);
  await p.getByRole('button',{name:'Убрать из избранного: Жим лёжа',exact:true}).click();
  await expect(p.getByRole('heading',{name:'Пока нет избранных упражнений'})).toBeVisible();
  await p.getByRole('button',{name:'Показать все упражнения'}).click();
  await p.getByRole('button',{name:'Грудь',exact:true}).click();
  await p.getByRole('combobox',{name:'Оборудование',exact:true}).selectOption('штанга');
  assert((await p.locator('.lib-exercises li').count())>0);
  await p.getByRole('button',{name:/Шаблоны 4/}).click();
  await p.screenshot({path:'output/library-review/templates-mobile.png'});
  await p.getByRole('button',{name:'Создать шаблон',exact:true}).click();
  await p.getByRole('button',{name:'Сохранить шаблон',exact:true}).click();
  await expect(p.getByRole('alert')).toContainText('Введите название');
  await p.getByLabel('Название шаблона',{exact:true}).fill('Моя силовая');
  await p.getByRole('button',{name:'Добавить упражнения',exact:true}).click();
  const done=p.getByRole('button',{name:/Готово ·/});
  await expect(done).toBeInViewport();
  const search=p.getByRole('searchbox',{name:'Поиск упражнений для шаблона'});
  await search.fill('присед');
  await p.getByRole('button',{name:'Приседания со штангой Ноги · штанга',exact:true}).click();
  await expect(search).toHaveValue('присед');
  await search.fill('планка');
  await p.getByRole('button',{name:'Планка Кор · вес тела',exact:true}).click();
  await done.click();
  await p.getByLabel('Подходы: Приседания со штангой',{exact:true}).fill('4');
  await p.getByLabel('Вес, кг: Приседания со штангой',{exact:true}).fill('32,5');
  await p.getByLabel('Повторения: Приседания со штангой',{exact:true}).fill('8–10');
  await p.getByLabel('Время, сек: Планка',{exact:true}).fill('45');
  await p.getByRole('button',{name:'Выше: Планка',exact:true}).click();
  await expect(p.locator('.builder-exercise h3').first()).toHaveText('Планка');
  await p.evaluate(()=>document.querySelector('.lib-body').scrollTop=0);
  await p.screenshot({path:'output/library-review/builder-mobile.png'});
  await p.reload();
  await p.getByRole('button',{name:'Библиотека',exact:true}).click();
  await p.getByRole('button',{name:/Шаблоны 4/}).click();
  await p.getByRole('button',{name:/Моя силовая Незавершённый черновик/}).click();
  await expect(p.getByLabel('Название шаблона',{exact:true})).toHaveValue('Моя силовая');
  await expect(p.locator('.builder-exercise h3').first()).toHaveText('Планка');
  await p.getByRole('button',{name:'Сохранить шаблон',exact:true}).click();
  await expect(p.getByRole('heading',{name:'Моя силовая',exact:true})).toBeVisible();
  await expect(p.locator('.lib-plan-list')).toContainText('45 сек');
  await expect(p.locator('.lib-plan-list')).toContainText('32,5 кг');
  await p.getByRole('button',{name:'Создать занятие с этим планом'}).click();
  assert.equal(await p.evaluate(()=>Store.get().newSession.program),'Моя силовая');
  await p.reload();await p.getByRole('button',{name:'Библиотека',exact:true}).click();await p.getByRole('button',{name:/Шаблоны 5/}).click();
  await expect(p.locator('.lib-template-card').filter({hasText:'Моя силовая'})).toHaveCount(1);
  for (const width of [320,390,1440]) {
   await p.setViewportSize({width,height:900});
   await p.getByRole('button',{name:/Упражнения 81/}).click();
   const overflow=await p.locator('.library-screen').evaluate(el=>el.scrollWidth>el.clientWidth+1);
   assert.equal(overflow,false,`No page overflow at ${width}`);
   if(width>600) await p.locator('.tabbar [data-id="t-library"]').scrollIntoViewIfNeeded();
   await expect(p.locator('.tabbar [data-id="t-library"]')).toBeInViewport();
   if(width===320) await p.screenshot({path:'output/library-review/exercises-320.png'});
   if(width===1440) await p.screenshot({path:'output/library-review/exercises-desktop.png',fullPage:true});
  }
  assert.deepEqual(errors,[]);
  console.log('PASS: search, combined filters, favorites/empty state, validation, multiple selection, visible Done button, reorder, numeric fields, draft reload, saved template reload, session selection, 320/390/1440px layout, no browser errors.');
 } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
