const { chromium, expect } = require('@playwright/test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const base = process.env.PROTOTYPE_URL || 'http://127.0.0.1:8777/prototype-fresh/';
const out = 'prototype-fresh/review/12-mascot-video';
fs.mkdirSync(out, { recursive: true });
(async () => {
  const browser = await chromium.launch();
  const errors = [];
  const report = [];
  async function page(options = {}, query = '') {
    const context = await browser.newContext({ viewport: { width: 390, height: 844 }, ...options });
    const p = await context.newPage();
    p.on('pageerror', e => errors.push(e.message));
    await p.goto(`${base}?visual=instrument${query}`);
    await p.evaluate(() => Store.set({ screen: 't-profile', role: 'trainer' }));
    await p.locator('[data-theme-choice="light"]').click();
    await p.evaluate(() => Store.set({ screen: 't-welcome', role: 'trainer' }));
    await expect(p.locator('.welcome')).toBeVisible();
    return p;
  }
  try {
    const p = await page();
    await expect(p.locator('[data-mascot="wave"]')).toHaveAttribute('data-playback', 'playing');
    await p.waitForTimeout(600);
    const before = await p.locator('video').evaluate(v => { window.testClip = v; return v.currentTime; });
    assert(before > 0);
    await p.evaluate(() => Store.set({ toast: { text: 'Проверка', at: Date.now() } }));
    await p.waitForTimeout(250);
    assert(await p.locator('video').evaluate(v => v === window.testClip && v.currentTime > 0));
    await p.evaluate(() => Store.set({ toast: null }));
    await p.waitForTimeout(150);
    await p.screenshot({ path: `${out}/wave-light-390.png` });
    await expect(p.locator('[data-mascot="wave"]')).toHaveAttribute('data-playback', 'finished', { timeout: 8000 });
    await expect(p.locator('video')).toHaveCount(0);
    await p.evaluate(() => Store.set({ toast: null }));
    await p.waitForTimeout(150);
    await expect(p.locator('video')).toHaveCount(0);
    report.push('Wave plays once and survives a screen rerender without restarting.');
    await p.locator('[data-act="welcome.next"]').click();
    await p.locator('[data-act="welcome.next"]').click();
    await p.locator('[data-act="welcome.next"]').click();
    await p.locator('[data-act="welcome.later"]').click();
    await expect(p.locator('[data-mascot="thumbs"]')).toHaveAttribute('data-playback', 'playing');
    await p.waitForTimeout(500);
    await p.screenshot({ path: `${out}/thumbs-light-390.png` });
    await p.evaluate(() => Store.set({ screen: 't-profile' }));
    await p.locator('[data-theme-choice="dark"]').click();
    await p.evaluate(() => Store.set({ screen: 't-welcome', welcome: { ...Store.get().welcome, step: 0 } }));
    await expect(p.locator('[data-mascot="wave"]')).toHaveAttribute('data-playback', 'playing');
    await p.waitForTimeout(500);
    await p.screenshot({ path: `${out}/wave-dark-390.png` });
    await p.evaluate(() => Store.set({ welcome: { ...Store.get().welcome, step: 4 } }));
    await expect(p.locator('[data-mascot="thumbs"]')).toHaveAttribute('data-playback', 'playing');
    await p.waitForTimeout(500);
    await p.screenshot({ path: `${out}/thumbs-dark-390.png` });
    await p.evaluate(() => Store.set({ screen: 't-today' }));
    await p.waitForTimeout(100);
    await p.evaluate(() => Fx.celebrate());
    await expect(p.locator('.fx-celebrate video')).toBeAttached();
    await p.waitForTimeout(1800);
    await p.screenshot({ path: `${out}/jump-dark-390.png` });
    await expect(p.locator('.fx-celebrate')).toHaveCount(0, { timeout: 7000 });
    await p.evaluate(() => Store.set({ screen: 't-profile' }));
    await p.locator('[data-theme-choice="light"]').click();
    await p.evaluate(() => Store.set({ screen: 't-today' }));
    await p.waitForTimeout(100);
    await p.evaluate(() => Fx.celebrate());
    await expect(p.locator('.fx-celebrate video')).toBeAttached();
    await p.waitForTimeout(1800);
    await p.screenshot({ path: `${out}/jump-light-390.png` });
    await p.evaluate(() => Store.preferences.toggleCalm());
    await expect(p.locator('.panda__media')).toHaveCount(0);
    await expect(p.locator('.fx-celebrate')).toBeHidden();
    await p.evaluate(() => Store.preferences.toggleCalm());
    await expect(p.locator('.fx-celebrate')).toHaveCount(0, { timeout: 7000 });
    report.push('Trainer onboarding advances to thumbs; celebration plays jump and removes its layer.');
    for (const screen of ['c-first', 'c-home', 't-inbox']) {
      await p.evaluate(screen => Store.set({ screen, role: screen.startsWith('c-') ? 'client' : 'trainer', scenario: 'empty' }), screen);
      await p.waitForTimeout(100);
      await expect(p.locator('.panda__media')).toHaveCount(0);
    }
    report.push('Client invitation, hero and empty screens have no video.');
    for (const width of [320, 1440]) {
      await p.setViewportSize({ width, height: 900 });
      await p.evaluate(() => Store.set({ role: 'trainer', screen: 't-welcome', welcome: { ...Store.get().welcome, step: 0 } }));
      await expect(p.locator('.welcome')).toBeVisible();
      assert(await p.locator('.welcome').evaluate(e => e.scrollWidth <= e.clientWidth + 1));
    }
    for (const [label, options, query] of [['reduced', { reducedMotion: 'reduce' }, ''], ['calm', {}, '&calm=1']]) {
      const q = await page(options, query);
      const mediaRequests = [];
      q.on('request', r => { if (/\.(webm|webp)(\?|$)/.test(r.url())) mediaRequests.push(r.url()); });
      await q.reload();
      await q.evaluate(() => Store.set({ screen: 't-welcome', role: 'trainer' }));
      await expect(q.locator('.welcome')).toBeVisible();
      await expect(q.locator('.panda__media')).toHaveCount(0);
      await q.evaluate(() => Fx.celebrate());
      await expect(q.locator('.fx-celebrate')).toHaveCount(0);
      assert.equal(mediaRequests.length, 0);
      await q.screenshot({ path: `${out}/${label}-390.png` });
      await q.context().close();
      report.push(`${label}: static PNG, no media downloads or celebration.`);
    }
    const safari = await page({ userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Safari/605.1.15' });
    await expect(safari.locator('img.panda__media')).toHaveAttribute('src', /wave.webp$/);
    await expect(safari.locator('[data-mascot="wave"]')).toHaveAttribute('data-playback', 'playing');
    await safari.screenshot({ path: `${out}/webp-fallback-390.png` });
    await expect(safari.locator('img.panda__media')).toHaveCount(0, { timeout: 8000 });
    report.push('Safari user-agent fallback: WebP plays once, then poster (Chromium simulation, not native Safari).');
    await p.setViewportSize({ width: 390, height: 844 });
    await p.route('**/video/*.webm', route => route.abort());
    await p.reload();
    await p.evaluate(() => Store.set({ screen: 't-welcome', role: 'trainer' }));
    await expect(p.locator('[data-mascot="wave"]')).toHaveAttribute('data-playback', 'finished');
    await expect(p.locator('.panda__poster')).toBeVisible();
    report.push('Failed media request leaves a visible poster.');
    await p.unroute('**/video/*.webm');
    await p.reload();
    await p.evaluate(() => Store.set({ screen: 't-welcome', role: 'trainer' }));
    await expect(p.locator('[data-mascot="wave"]')).toHaveAttribute('data-playback', 'playing');
    await p.emulateMedia({ reducedMotion: 'reduce' });
    await expect(p.locator('.panda__media')).toHaveCount(0);
    report.push('Changing reduced motion stops active playback immediately.');
    assert.deepEqual(errors, []);
    fs.writeFileSync(`${out}/report.json`, JSON.stringify({ report, errors }, null, 2));
    console.log(report.join('\n'));
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exitCode = 1; });
