export const trainerClients = {
  title: 'Клиенты',
  loading: 'Загружаем список…',
  database: '{{clients}} в вашей базе',
  clients_one: '{{count}} клиент',
  clients_few: '{{count}} клиента',
  clients_many: '{{count}} клиентов',
  clients_other: '{{count}} клиента',
  add: 'Добавить клиента',
  search: 'Поиск клиента по имени или телефону',
  placeholder: 'Имя или телефон',
  clear: 'Очистить поиск',
  filters: 'Фильтр клиентов',
  all: 'Все',
  due: 'К оплате',
  unscheduled: 'Без записи',
  alphabet: 'По алфавиту',
  results: 'Результаты поиска',
  offline: 'Нет связи. Показан сохранённый список клиентов.',
  noPlan: 'Нет пакета',
  remaining: 'Осталось',
  sessions_one: 'занятие',
  sessions_few: 'занятия',
  sessions_many: 'занятий',
  sessions_other: 'занятия',
  noNext: 'Нет будущих занятий',
  next: '{{date}} · {{time}}',
  nextGroup: '{{date}} · {{time}} · мини-группа',
  today: 'Сегодня',
  september15: '15 сен',
  payment: 'К оплате {{amount}} ₸',
  disconnected: 'Не подключён',
  notFound: 'Клиент не найден',
  notFoundHint: 'Проверьте имя или телефон. Можно также сбросить фильтры.',
  noResults: 'В этом списке пока никого',
  noResultsHint: 'Все клиенты доступны в общем списке.',
  first: 'Ваш первый клиент',
  firstHint:
    'Создайте карточку. Программу и занятия можно добавить до подключения клиента.',
  reset: 'Сбросить поиск и фильтры',
  dash: '—',
  people: {
    c1: { name: 'Айгерим Бекова', initials: 'АБ', program: 'Низ А' },
    c2: { name: 'Арман Оспанов', initials: 'АО', program: 'Сила 5×5' },
    c3: { name: 'Алия Нурлановa', initials: 'АН', program: 'Низ А' },
    c4: { name: 'Мади Касымов', initials: 'МК', program: 'Верх Б' },
    c5: { name: 'Дана Ержанова', initials: 'ДЕ', program: 'Full Body' },
    c6: {
      name: 'Тимур Ахметов',
      initials: 'ТА',
      program: 'Программа не назначена',
    },
  },
};
