export const clientDetails = {
  sessionDate: '{{date}} · {{start}}–{{end}}',
  sessionMeta: '{{program}} · {{kind}}',
  paymentMeta: '{{date}} · {{method}}',
  noteMeta: '{{date}} · {{time}} · {{visibility}}',
  workingWeight: 'Рабочий вес',
  chartRange: '{{first}} — {{last}} · записей: {{count}}',
  chartHint:
    'Точки — отдельные записи, точные значения ниже. Шкала от нуля, вес в кг. Больший вес сам по себе не означает лучший результат: важны повторы и техника.',
  valuesHint: 'Точки — отдельные записи, точные значения ниже. Шкала от нуля.',
  cancelled: 'Отменено',
  awaitingClient: 'Ждём ответа клиента',
  proposed: 'Ждём согласия',
  back: 'Назад',
  actions: 'Действия',
  invite: 'Пригласить',
  sections: 'Разделы клиента',
  sessions: 'Занятия',
  program: 'Программа',
  progress: 'Прогресс',
  billing: 'Оплаты',
  notes: 'Заметки',
  balance: 'Остаток',
  due: 'К оплате',
  noPurchase: 'Без покупки',
  unavailable: 'Действие пока недоступно в демо.',
  loading: 'Загрузка карточки клиента',
  offline: 'Нет связи. Показаны сохранённые данные.',
  notFound: 'Клиент не найден',
  noSessions: 'Нет занятий',
  noSessionsHint: 'Создайте занятие и назначьте программу.',
  create: 'Создать занятие',
  later: 'Программа позже',
  group: 'мини-группа',
  personal: 'индивидуальное',
  confirmed: 'Подтверждено',
  awaiting: 'Ждёт вашего ответа',
  template:
    'Текущий шаблон: {{program}}. Изменение назначенной программы не переписывает прошлые занятия.',
  noProgram: 'Программы нет',
  noProgramHint:
    'Назначьте шаблон из библиотеки — программа применится к будущим занятиям.',
  library: 'Открыть библиотеку',
  noProgress: 'Пока нет данных',
  noProgressHint:
    'История появится после первых записанных занятий. Отсутствие данных — не ноль.',
  noPurchases: 'Покупок нет',
  noPurchasesHint: 'Разовое занятие или пакет появятся здесь после покупки.',
  paid: 'Оплачено',
  cost: 'Стоимость',
  received: 'Получено',
  lessons: 'Занятий',
  used: '{{units}} · использовано {{used}}',
  expires: 'Срок',
  unlimited: 'без срока',
  recordPayment: 'Записать оплату',
  payments: 'История оплат',
  noPayments: 'Оплат пока нет.',
  recorded: 'Записано',
  planGoal: 'План и цель',
  goal: 'Цель',
  completed: 'Проведено',
  completedValue: '{{count}} занятий',
  joined: 'В приложении',
  since: 'с {{date}}',
  privateNote: 'Заметка тренера · приватно',
  publicNote: 'Комментарий для клиента',
  noNotes: 'Заметок нет.',
  noComment: 'Пусто. Клиент увидит этот текст.',
  dash: '—',
  money: '{{amount}} ₸',
  exercisePlan: '{{sets}} × {{reps}}',
  weight: '{{amount}} кг',
  latest: 'Последняя запись · {{date}}',
  sets: 'Подходов: {{count}}',
  oneRecord: 'Пока одна запись. Сравнение появится после следующей.',
  records: 'Записи по упражнению',
  date: 'Дата',
  weightColumn: 'Вес, кг',
  setsColumn: 'Подходы',
  comparison: 'Упражнение для сравнения',
  change: '{{delta}} {{unit}} с {{date}}',
  valueColumn: 'Результат',
  people: {
    c1: {
      plan: 'Пакет 12 занятий',
      goal: 'Похудение · 3 раза в неделю',
      note: 'Правое колено — не больше 90°, следить за разминкой.',
      comment: 'Прошу писать время переноса минимум за 12 часов.',
    },
    c2: {
      plan: 'Пакет 8 занятий',
      goal: 'Сила · жим и присед',
      note: 'Поясница — не добавлять вес без страховки.',
      comment: '',
    },
    c3: {
      plan: 'Пакет 12 занятий',
      goal: 'Тонус · 2 раза в неделю',
      note: '',
      comment: 'Удобно после 19:00.',
    },
    c4: {
      plan: 'Разовые занятия',
      goal: 'Набор массы · 3 раза в неделю',
      note: 'Хочет жим — следить за техникой плеча.',
      comment: '',
    },
    c5: {
      plan: 'Пакет 12 занятий',
      goal: 'Общая форма · 2–3 раза в неделю',
      note: '',
      comment: '',
    },
    c6: { plan: 'Без покупки', goal: '', note: '', comment: '' },
    c7: { plan: 'Без покупки', goal: '', note: '', comment: '' },
  },
  paymentMethods: {
    c1: 'Kaspi · Первая часть',
    c2: 'Перевод',
    c4: 'Наличные · Остаток 6 000',
    c5: 'Kaspi',
  },
};
