import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  rows: { padding: 6 },
  bookingRow: { flexDirection: 'column', alignItems: 'stretch', gap: 10 },
  bookingInfo: { gap: 2 },
  bookingMeta: { fontFamily: 'Inter_500Medium', lineHeight: 20.3 },
  bookingTitle: { fontSize: 15, lineHeight: 21.75 },
  metricLabel: { letterSpacing: 1.4 },
  root: { flex: 1 },
  body: { paddingBottom: 24 },
  topbar: {
    minHeight: 58,
    paddingHorizontal: 8,
    paddingTop: 10,
    paddingBottom: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  iconButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  header: { paddingTop: 6, paddingHorizontal: 16 },
  identity: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  flex: { flex: 1 },
  avatar: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
  },
  initials: { fontFamily: 'Montserrat_800ExtraBold', fontSize: 15 },
  name: {
    fontFamily: 'Montserrat_800ExtraBold',
    fontSize: 22,
    lineHeight: 31.9,
    letterSpacing: -0.4,
  },
  small: { fontSize: 14, lineHeight: 21 },
  metrics: { flexDirection: 'row', gap: 10, marginTop: 16 },
  metric: { flex: 1, paddingVertical: 13, paddingHorizontal: 14 },
  label: {
    fontFamily: 'Inter_700Bold',
    fontSize: 14,
    lineHeight: 20.3,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  balance: {
    fontFamily: 'Montserrat_800ExtraBold',
    fontSize: 24,
    lineHeight: 34.8,
    letterSpacing: -1,
    marginTop: 4,
  },
  due: {
    fontFamily: 'Montserrat_800ExtraBold',
    fontSize: 19,
    lineHeight: 27.55,
    letterSpacing: -0.6,
    marginTop: 6,
  },
  tabs: { paddingTop: 18, paddingBottom: 10, paddingHorizontal: 16, gap: 8 },
  chip: {
    minHeight: 44,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 9999,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chipText: { fontFamily: 'Inter_600SemiBold', fontSize: 14, lineHeight: 20.3 },
  content: { paddingHorizontal: 16 },
  stack: { gap: 12 },
  sessionRow: {
    paddingVertical: 14,
    paddingHorizontal: 12,
    flexDirection: 'row',
    gap: 14,
    alignItems: 'center',
  },
  rowTitle: { fontFamily: 'Inter_700Bold', fontSize: 15.5, lineHeight: 22.475 },
  heading: { fontFamily: 'Inter_600SemiBold', fontSize: 16, lineHeight: 22.4 },
  empty: { paddingVertical: 28, alignItems: 'center', gap: 10 },
  center: { textAlign: 'center' },
  notice: { padding: 14, borderRadius: 16, flexDirection: 'row', gap: 10 },
  noticeRow: { flexDirection: 'row', gap: 10 },
  numberLead: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
  },
  trophy: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  kv: {
    flexDirection: 'row',
    gap: 12,
    paddingVertical: 11,
    borderBottomWidth: 1,
  },
  kvValue: { fontFamily: 'Inter_700Bold', flex: 1, textAlign: 'right' },
  purchaseHeader: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  loading: { marginTop: 40 },
  progress: { gap: 14 },
  picker: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  progressValue: {
    fontFamily: 'Montserrat_800ExtraBold',
    fontSize: 36,
    lineHeight: 39.6,
  },
  valueRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 8,
    marginTop: 18,
  },
  tableRow: { flexDirection: 'row', paddingVertical: 12, borderBottomWidth: 1 },
  tableCell: { flex: 1, textAlign: 'right' },
  change: { paddingTop: 12, borderTopWidth: 1, marginTop: 14 },
});
