import { StyleSheet } from 'react-native';
export const styles = StyleSheet.create({
  root: { flex: 1 },
  body: { paddingBottom: 20 },
  topbar: {
    paddingVertical: 10,
    paddingLeft: 18,
    paddingRight: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  trainer: { flexDirection: 'row', alignItems: 'center', gap: 9 },
  avatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  initials: {
    color: '#ffffff',
    fontFamily: 'Inter_800ExtraBold',
    fontSize: 14,
    letterSpacing: 0.3,
  },
  trainerText: { fontSize: 14, lineHeight: 16.8 },
  iconButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    paddingTop: 2,
    paddingHorizontal: 18,
    paddingBottom: 12,
    fontFamily: 'Montserrat_800ExtraBold',
    fontSize: 27,
    lineHeight: 28.08,
    letterSpacing: -0.5,
  },
  page: { paddingHorizontal: 16 },
  note: {
    marginTop: 2,
    marginHorizontal: 4,
    marginBottom: 16,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 14,
    fontSize: 14,
    lineHeight: 19.6,
  },
  heading: { marginTop: 2, marginHorizontal: 4, marginBottom: 18 },
  name: {
    fontFamily: 'Montserrat_800ExtraBold',
    fontSize: 21,
    lineHeight: 27.3,
  },
  date: { marginTop: 6, fontSize: 14, lineHeight: 20.3 },
  rows: { padding: 6 },
  row: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    paddingVertical: 17,
    paddingHorizontal: 12,
  },
  lead: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  number: {
    fontFamily: 'Montserrat_800ExtraBold',
    fontSize: 14,
    lineHeight: 20.3,
    color: '#2238b0',
  },
  main: { flex: 1 },
  rowTitle: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 15.5,
    lineHeight: 21.7,
    letterSpacing: 0.1,
  },
  rowMeta: {
    marginTop: 5,
    fontFamily: 'Inter_500Medium',
    fontSize: 14,
    lineHeight: 20.3,
  },
  right: { paddingTop: 5 },
  footnote: { marginTop: 12, fontSize: 14, lineHeight: 21.7 },
  empty: {
    paddingTop: 8,
    paddingHorizontal: 12,
    paddingBottom: 20,
    alignItems: 'center',
  },
  mascot: { marginBottom: 0 },
  emptyTitle: {
    marginTop: 14,
    fontFamily: 'Inter_700Bold',
    fontSize: 17,
    lineHeight: 23.8,
    textAlign: 'center',
  },
  emptyHint: {
    marginTop: 6,
    fontSize: 14,
    lineHeight: 21.7,
    textAlign: 'center',
  },
  schedule: { marginTop: 14 },
  offline: {
    marginVertical: 12,
    marginHorizontal: 16,
    padding: 12,
    borderRadius: 12,
    fontSize: 14,
    lineHeight: 20.3,
  },
  skeletonRow: {
    paddingVertical: 14,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  skeletonCircle: { width: 42, height: 42, borderRadius: 21 },
  skeletonTitle: { width: '60%', height: 14, borderRadius: 10 },
  skeletonMeta: { width: '40%', height: 12, borderRadius: 10, marginTop: 8 },
  kv: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 },
  guide: { width: 180, height: 180, alignSelf: 'center' },
  step: { fontSize: 14, lineHeight: 21.7 },
});
