export const clientHistory = {
  loadMore: 'Показать ещё',
  emptyFinishedText:
    'Здесь появятся результаты завершённых занятий и открытые заметки тренера.',
  openJournal: '{{date}} · {{start}}',
  actualSet: 'Подход {{position}}',
  actualReps: '{{value}} повт.',
  actualSeconds: '{{value}} сек',
  actualWeight: '{{value}} кг',
  repsMissing: 'Повторы не записаны',
  secondsMissing: 'Время не записано',
  weightMissing: 'Вес не записан',
  noResults: 'Результаты не записаны',
  skipped: 'Пропущено',
  replaced: 'Заменено',
  title: 'История',
  trainerLabel: 'Ваш тренер',
  trainer: 'Данияр',
  initials: 'ДС',
  notifications: 'Уведомления',
  loading: 'Загрузка раздела',
  offline: 'Нет связи. Показаны сохранённые данные.',
  sessionsTitle: 'Прошедшие занятия',
  chargesTitle: 'Списания и возвраты',
  program: 'Низ А',
  personal: 'Индивидуальное занятие',
  unmarked: 'Нет отметки',
  finished: 'Журнал завершён',
  noProgram: 'Без программы',
  group: 'Мини-группа',
  noteTrainer: 'Тренер:',
  sessionDate: 'пн, 14 сен · 18:00',
  day: '14',
  month: 'сен',
  time: '18:00',
  chargeReason: 'Проведённое занятие',
  chargeDateRecent: '9 сен',
  chargeDateEarlier: '2 сен',
  chargeValue: '−1',
  chargeLabel: 'Списание: 1',
  emptySessionsTitle: 'Занятий пока нет',
  emptySessionsText:
    'Здесь появятся прошедшие и отменённые записи из расписания.',
  emptyChargesTitle: 'Списаний пока нет',
  emptyChargesText:
    'Изменения остатка пакета будут показаны отдельно от посещений.',
  footnote:
    'Списание не подтверждает посещение: оно может быть связано с неявкой.',
} as const;
