import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  root: { flex: 1 },
  body: { paddingBottom: 20 },
  topbar: {
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 18,
    paddingRight: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  trainer: { flexDirection: 'row', alignItems: 'center', gap: 9 },
  avatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#262b45',
  },
  initials: {
    color: '#ffffff',
    fontFamily: 'Inter_800ExtraBold',
    fontSize: 14,
    letterSpacing: 0.3,
  },
  trainerText: { fontSize: 14, lineHeight: 16.8 },
  iconButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    paddingTop: 2,
    paddingHorizontal: 18,
    paddingBottom: 12,
    fontFamily: 'Montserrat_800ExtraBold',
    fontSize: 27,
    lineHeight: 28.08,
    letterSpacing: -0.5,
  },
  page: { paddingHorizontal: 16 },
  sectionTitle: {
    marginHorizontal: 4,
    marginBottom: 12,
    fontSize: 16,
    lineHeight: 21.6,
    fontFamily: 'Inter_700Bold',
  },
  nextSection: { marginTop: 24 },
  entry: {
    flexDirection: 'row',
    gap: 16,
    paddingVertical: 20,
    paddingHorizontal: 16,
  },
  date: {
    width: 64,
    paddingRight: 12,
    borderRightWidth: 1,
    alignItems: 'center',
  },
  day: {
    fontFamily: 'Montserrat_800ExtraBold',
    fontSize: 26,
    lineHeight: 26,
    fontVariant: ['tabular-nums'],
  },
  month: { fontSize: 14, lineHeight: 20.3, marginTop: 4 },
  time: {
    fontSize: 14,
    lineHeight: 20.3,
    marginTop: 10,
    fontVariant: ['tabular-nums'],
  },
  record: { flex: 1, minWidth: 0 },
  program: { fontFamily: 'Inter_700Bold', fontSize: 15, lineHeight: 21.75 },
  sessionKind: { fontSize: 14, lineHeight: 21, marginTop: 6, marginBottom: 10 },
  rowsCard: { padding: 6 },
  row: {
    paddingVertical: 14,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  rowMain: { flex: 1, minWidth: 0 },
  rowTitle: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 15.5,
    lineHeight: 22.475,
    letterSpacing: 0.1,
  },
  rowMeta: {
    fontFamily: 'Inter_500Medium',
    fontSize: 14,
    lineHeight: 20.3,
    marginTop: 2,
  },
  unit: {
    fontFamily: 'Montserrat_700Bold',
    fontSize: 18,
    lineHeight: 21.6,
    fontVariant: ['tabular-nums'],
  },
  footnote: { fontSize: 14, lineHeight: 21.7, marginTop: 12 },
  empty: { padding: 20, borderRadius: 24 },
  lead: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  emptyTitle: {
    fontFamily: 'Inter_700Bold',
    fontSize: 17,
    lineHeight: 23.8,
    marginTop: 14,
  },
  emptyText: { fontSize: 14, lineHeight: 21.7, marginTop: 6 },
  offline: {
    marginVertical: 12,
    marginHorizontal: 16,
    padding: 12,
    borderRadius: 12,
    fontSize: 14,
    lineHeight: 20.3,
  },
  skeletonCircle: { width: 42, height: 42, borderRadius: 21 },
  skeletonTitle: { width: '60%', height: 14, borderRadius: 10 },
  skeletonMeta: { width: '40%', height: 12, borderRadius: 10, marginTop: 8 },
});
