export const profiles = {
  title: 'Профиль',
  trainer: 'Данияр Сериков',
  trainerShort: 'Данияр',
  trainerInitials: 'ДС',
  trainerLabel: 'Ваш тренер',
  occupation: 'Независимый тренер',
  today: 'занятий сегодня',
  awaiting: 'ждут ответа',
  clients: 'клиентов в базе',
  library: 'Библиотека и шаблоны',
  exercises: 'Мои упражнения',
  billing: 'Пакеты и оплаты',
  notifications: 'Уведомления',
  calm: 'Спокойный интерфейс',
  theme: 'Тема',
  auto: 'По роли',
  dark: 'Тёмная',
  light: 'Светлая',
  client: 'Айгерим Бекова',
  clientInitials: 'АБ',
  since: 'Начало занятий: март 2025',
  personal: 'Личные данные',
  phoneLabel: 'Телефон',
  phone: '+7 701 214 88 03',
  coach: 'Тренер',
  packageLabel: 'Пакет занятий',
  package: 'Пакет 12 занятий',
  remaining: 'из 12 занятий осталось',
  dueLabel: 'К оплате',
  due: '40 000 ₸',
  payment: 'Оплату согласуйте с тренером.',
  empty: 'Пакета пока нет',
  emptyHint: 'Условия и количество занятий можно согласовать с тренером.',
  settings: 'Настройки',
  loading: 'Загрузка раздела',
  offline: 'Нет связи. Показаны сохранённые данные.',
  unavailable: 'Пока недоступно',
};
