import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  root: { flex: 1 },
  trainerHeader: {
    minHeight: 44,
    paddingTop: 10,
    paddingBottom: 2,
    alignItems: 'center',
  },
  trainerTitle: {
    fontFamily: 'Montserrat_700Bold',
    fontSize: 17,
    lineHeight: 24.65,
    letterSpacing: -0.2,
  },
  trainerBody: { paddingTop: 4, paddingHorizontal: 16, paddingBottom: 20 },
  trainerPerson: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingTop: 8,
    paddingHorizontal: 6,
    paddingBottom: 20,
  },
  trainerName: {
    fontFamily: 'Montserrat_800ExtraBold',
    fontSize: 22,
    lineHeight: 31.9,
    letterSpacing: -0.4,
  },
  occupation: {
    fontFamily: 'Inter_500Medium',
    marginTop: 2,
    fontSize: 14,
    lineHeight: 20.3,
  },
  lead: {
    width: 42,
    height: 42,
    borderRadius: 21,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  leadSmall: { width: 34, height: 34, borderRadius: 17 },
  leadText: {
    fontFamily: 'Montserrat_800ExtraBold',
    fontSize: 15,
    lineHeight: 21.75,
  },
  stats: { flexDirection: 'row', gap: 10 },
  stat: { flex: 1, paddingTop: 15, paddingHorizontal: 8, paddingBottom: 13 },
  statValue: {
    fontFamily: 'Montserrat_900Black',
    fontSize: 25,
    lineHeight: 27.5,
    letterSpacing: -1,
    textAlign: 'center',
  },
  statLabel: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 14,
    lineHeight: 20.3,
    marginTop: 4,
    textAlign: 'center',
  },
  rows: { padding: 6, marginVertical: 16 },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingVertical: 14,
    paddingHorizontal: 12,
  },
  rowTitle: {
    flex: 1,
    fontFamily: 'Inter_600SemiBold',
    fontSize: 15.5,
    lineHeight: 22.475,
    letterSpacing: 0.1,
  },
  preference: {
    minHeight: 56,
    paddingVertical: 12,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    borderWidth: 1,
    borderRadius: 14,
    marginBottom: 12,
  },
  preferenceLabel: { flexShrink: 1 },
  track: { width: 44, height: 26, borderRadius: 999, padding: 3 },
  thumb: { width: 20, height: 20, borderRadius: 10 },
  theme: { paddingVertical: 8, paddingRight: 8, flexWrap: 'wrap', rowGap: 8 },
  segments: { flexDirection: 'row', borderRadius: 10, padding: 2, gap: 2 },
  segment: {
    minHeight: 44,
    paddingHorizontal: 12,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  segmentLabel: {
    fontFamily: 'Inter_500Medium',
    fontSize: 14,
    lineHeight: 20.3,
  },
  clientTopbar: {
    paddingVertical: 10,
    paddingLeft: 18,
    paddingRight: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  chip: { flexDirection: 'row', alignItems: 'center', gap: 9 },
  chipAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  chipInitials: {
    color: '#ffffff',
    fontFamily: 'Inter_800ExtraBold',
    fontSize: 14,
    letterSpacing: 0.3,
  },
  chipText: { fontSize: 14, lineHeight: 16.8 },
  iconButton: {
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    paddingTop: 2,
    paddingHorizontal: 18,
    paddingBottom: 12,
    fontFamily: 'Montserrat_800ExtraBold',
    fontSize: 27,
    lineHeight: 28.08,
    letterSpacing: -0.5,
  },
  clientContent: { paddingHorizontal: 16 },
  clientPerson: { flexDirection: 'row', gap: 12, alignItems: 'center' },
  personText: { flex: 1 },
  clientName: {
    fontFamily: 'Montserrat_800ExtraBold',
    fontSize: 20,
    lineHeight: 26,
  },
  small: { fontSize: 14, lineHeight: 20.3 },
  since: { marginTop: 5 },
  section: { marginTop: 24 },
  sectionTitle: {
    fontFamily: 'Inter_700Bold',
    fontSize: 16,
    lineHeight: 21.6,
    marginHorizontal: 4,
    marginBottom: 12,
  },
  details: { paddingHorizontal: 18, paddingVertical: 33, gap: 16 },
  detailLabel: { fontSize: 14, lineHeight: 20.3, marginBottom: 5 },
  detailValue: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 14,
    lineHeight: 20.3,
  },
  package: { padding: 16 },
  packageTitle: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 14,
    lineHeight: 20.3,
  },
  packageValue: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 8,
    marginVertical: 12,
    flexWrap: 'wrap',
  },
  remaining: {
    fontFamily: 'Montserrat_800ExtraBold',
    fontSize: 30,
    lineHeight: 33,
  },
  meter: { height: 8, borderRadius: 999, overflow: 'hidden' },
  meterValue: { width: '58%', height: 8, borderRadius: 999 },
  payment: { marginTop: 18, paddingTop: 16, borderTopWidth: 1 },
  amount: { fontFamily: 'Montserrat_700Bold', fontSize: 22, lineHeight: 28.6 },
  footnote: { fontSize: 14, lineHeight: 21.7, marginTop: 15 },
  empty: { padding: 20, boxShadow: 'none' },
  emptyTitle: {
    fontFamily: 'Inter_700Bold',
    fontSize: 17,
    lineHeight: 23.8,
    marginTop: 14,
  },
  emptyHint: { fontSize: 14, lineHeight: 21.7, marginTop: 6 },
  notifications: { marginTop: 20 },
  body: { paddingBottom: 20 },
  offline: {
    marginVertical: 12,
    marginHorizontal: 16,
    padding: 12,
    borderRadius: 14,
    fontSize: 14,
    lineHeight: 20.3,
  },
  skeletonRows: { padding: 6 },
  skeletonRow: {
    paddingVertical: 14,
    paddingHorizontal: 12,
    flexDirection: 'row',
    gap: 14,
    alignItems: 'center',
  },
  skeletonLines: { flex: 1, gap: 8 },
  skeletonLine: { height: 14, borderRadius: 6, width: '60%' },
  skeletonShort: { height: 12, borderRadius: 6, width: '40%' },
  roleSwitch: { marginTop: 20 },
});
