export const workspaceClientDetailsRu = {
  back: 'Назад',
  invite: 'Пригласить',
  inviteUnavailable: 'Приглашения пока недоступны',
  balance: 'Остаток',
  due: 'К оплате',
  unknown: '—',
  sections: 'Разделы клиента',
  tabs: {
    sessions: 'Занятия',
    program: 'Программа',
    progress: 'Прогресс',
    billing: 'Оплаты',
    notes: 'Заметки',
  },
  loading: 'Загружаем карточку клиента',
  errorTitle: 'Не удалось загрузить клиента',
  errorHint: 'Проверьте подключение и попробуйте ещё раз.',
  retry: 'Повторить',
  notFound: 'Клиент не найден',
  notFoundHint: 'Проверьте ссылку или вернитесь к списку клиентов.',
  noSessions: 'Нет занятий',
  noSessionsHint: 'Здесь появятся занятия этого клиента.',
  personal: 'индивидуальное',
  group: 'мини-группа',
  proposed: 'Предложено',
  confirmed: 'Подтверждено',
  cancelled: 'Отменено',
  unknownStatus: 'Статус неизвестен',
  noProgram: 'Программы нет',
  noProgramHint: 'Назначенная программа и упражнения появятся здесь.',
  currentProgram: 'Текущая программа',
  currentProgramName: 'Текущая программа: {{name}}',
  sessionTime: '{{date}} · {{start}}–{{end}}',
  exercisePlan: '{{sets}} × {{reps}}',
  seconds: 'сек',
  weight: '{{amount}} кг',
  progressUnavailable: 'История прогресса пока недоступна.',
  billingUnavailable: 'Данные об оплатах и пакетах пока недоступны.',
  notesUnavailable: 'Заметки клиента пока недоступны.',
  unavailableTitle: 'Данные пока недоступны',
  noPhone: 'Телефон не указан',
} as const;
