export const workspaceClientsRu = {
  back: 'Назад',
  title: 'Клиенты',
  loading: 'Загружаем список…',
  database: '{{clients}} в вашей базе',
  clients_one: '{{count}} клиент',
  clients_few: '{{count}} клиента',
  clients_many: '{{count}} клиентов',
  clients_other: '{{count}} клиента',
  add: 'Добавить клиента',
  search: 'Поиск клиента по имени или телефону',
  placeholder: 'Имя или телефон',
  clear: 'Очистить поиск',
  filters: 'Фильтр клиентов',
  dash: '—',
  all: 'Все',
  due: 'К оплате',
  unscheduled: 'Без записи',
  alphabet: 'По алфавиту',
  results: 'Результаты поиска',
  clientsCount_one: '{{count}} клиент',
  clientsCount_few: '{{count}} клиента',
  clientsCount_many: '{{count}} клиентов',
  clientsCount_other: '{{count}} клиента',
  billingUnknown: '—',
  noProgram: 'Программа не назначена',
  noNext: 'Нет будущих занятий',
  disconnected: 'Не подключён',
  retry: 'Повторить',
  readError: 'Не удалось загрузить список клиентов.',
  errorHint: 'Проверьте подключение и попробуйте ещё раз.',
  notFound: 'Клиент не найден',
  notFoundHint: 'Проверьте имя или телефон. Можно также сбросить фильтры.',
  noResults: 'В этом списке пока никого',
  noResultsHint: 'Все клиенты доступны в общем списке.',
  first: 'Ваш первый клиент',
  firstHint:
    'Создайте карточку. Программу и занятия можно добавить до подключения клиента.',
  reset: 'Сбросить поиск и фильтры',
  sheetTitle: 'Новый клиент',
  sheetNote: 'Начните с имени. Карточку можно вести до подключения клиента.',
  nameLabel: 'Имя и фамилия',
  namePlaceholder: 'Например, Алия Нурланова',
  create: 'Создать карточку',
  cancel: 'Отмена',
  nameRequired: 'Введите имя клиента.',
  saveError: 'Не удалось создать карточку. Попробуйте ещё раз.',
} as const;
