import { StyleSheet } from 'react-native';
export const styles = StyleSheet.create({
  root: { flex: 1 },
  flex: { flex: 1 },
  body: { padding: 20, paddingTop: 12, paddingBottom: 28 },
  heading: { paddingTop: 16, paddingBottom: 24 },
  eyebrow: {
    fontSize: 10,
    lineHeight: 14.5,
    fontWeight: '800',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  title: {
    fontFamily: 'Montserrat_800ExtraBold',
    fontWeight: '800',
    fontSize: 30,
    lineHeight: 34.5,
    letterSpacing: -0.9,
    marginVertical: 8,
  },
  subtitle: { fontSize: 13, lineHeight: 20.15, maxWidth: 280 },
  tabs: {
    flexDirection: 'row',
    padding: 4,
    gap: 4,
    borderRadius: 14,
    marginBottom: 20,
  },
  tab: {
    flex: 1,
    minHeight: 44,
    borderRadius: 11,
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabText: { fontSize: 13, lineHeight: 18.85, fontWeight: '700' },
  count: {
    fontSize: 11,
    lineHeight: 15.95,
    paddingVertical: 1,
    paddingHorizontal: 5,
    borderRadius: 5,
  },
  search: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderRadius: 14,
    minHeight: 50,
  },
  input: {
    flex: 1,
    minWidth: 0,
    height: 48,
    fontFamily: 'Inter_400Regular',
    fontSize: 13,
    padding: 0,
  },
  groups: { gap: 8, paddingTop: 16, paddingBottom: 8 },
  group: {
    minHeight: 44,
    paddingHorizontal: 15,
    borderWidth: 1,
    borderRadius: 24,
    justifyContent: 'center',
  },
  groupText: { fontSize: 12, lineHeight: 17.4, fontWeight: '700' },
  filters: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    columnGap: 12,
    paddingBottom: 12,
    borderBottomWidth: 1,
  },
  filter: { flexDirection: 'row', gap: 5, minHeight: 44, alignItems: 'center' },
  filterText: { fontSize: 11, lineHeight: 15.95, fontWeight: '600' },
  resultHeading: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    marginTop: 22,
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 16,
    lineHeight: 23.2,
    letterSpacing: -0.25,
    fontWeight: '800',
  },
  small: { fontSize: 11, lineHeight: 15.95 },
  list: { gap: 8 },
  exercise: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 8,
    borderRadius: 16,
    borderWidth: 1,
  },
  exerciseOpen: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
    minWidth: 0,
    minHeight: 68,
  },
  thumb: {
    width: 64,
    height: 64,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  thumbnail: {
    width: 64,
    height: 64,
    resizeMode: 'contain',
    backgroundColor: '#ffffff',
  },
  exerciseText: { flex: 1, minWidth: 0, gap: 5 },
  exerciseName: { fontSize: 13, fontWeight: '700', lineHeight: 17.55 },
  demoText: { fontSize: 10, lineHeight: 14.5, fontWeight: '600' },
  iconButton: {
    width: 44,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  create: { padding: 20, borderRadius: 20, marginBottom: 20 },
  createTitle: {
    fontFamily: 'Montserrat_800ExtraBold',
    fontWeight: '800',
    fontSize: 21,
    lineHeight: 30.45,
    letterSpacing: -0.5,
  },
  createText: {
    fontSize: 13,
    lineHeight: 20.15,
    marginTop: 8,
    marginBottom: 16,
  },
  templates: { gap: 14 },
  templateCard: { padding: 20, borderRadius: 20, borderWidth: 1 },
  templateTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  templateTitle: {
    fontFamily: 'Montserrat_800ExtraBold',
    fontWeight: '800',
    fontSize: 24,
    lineHeight: 34.8,
    letterSpacing: -0.6,
  },
  summary: { fontSize: 12, lineHeight: 17.4, marginTop: 6, marginBottom: 16 },
  preview: { gap: 8, borderTopWidth: 1, paddingTop: 14 },
  previewRow: { flexDirection: 'row', gap: 10 },
  previewText: { fontSize: 12, lineHeight: 17.4 },
  more: { fontSize: 11, lineHeight: 15.95, marginTop: 12 },
  empty: { alignItems: 'center', paddingVertical: 36, paddingHorizontal: 16 },
  emptyTitle: {
    fontSize: 16,
    lineHeight: 23.2,
    marginTop: 12,
    marginBottom: 8,
    textAlign: 'center',
    fontWeight: '700',
  },
  emptyText: {
    fontSize: 13,
    lineHeight: 20.8,
    marginBottom: 20,
    textAlign: 'center',
  },
  topbar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 12,
  },
  detailTitle: {
    fontFamily: 'Montserrat_800ExtraBold',
    fontWeight: '800',
    fontSize: 32,
    lineHeight: 36.8,
    marginVertical: 12,
    letterSpacing: -0.9,
  },
  description: { fontSize: 13, lineHeight: 20.8 },
  planSummary: {
    flexDirection: 'row',
    gap: 24,
    paddingVertical: 20,
    borderBottomWidth: 1,
    marginTop: 4,
    marginBottom: 20,
  },
  planRow: {
    flexDirection: 'row',
    gap: 12,
    paddingVertical: 16,
    borderBottomWidth: 1,
  },
  order: {
    width: 32,
    height: 32,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  planName: {
    fontSize: 14,
    lineHeight: 20.3,
    fontWeight: '700',
    marginBottom: 6,
  },
  footer: { paddingTop: 24 },
  guideImage: {
    width: 180,
    height: 180,
    alignSelf: 'center',
    backgroundColor: '#ffffff',
  },
});
