export const clientHome = {
  packages: 'Пакеты',
  activeUnits: 'из {{units}} занятий',
  serverDue: 'Долг: {{amount}}',
  namedGreeting: 'Привет, {{name}}',
  trainerLabel: 'Ваш тренер',
  trainer: 'Данияр',
  initials: 'ДС',
  notifications: 'Уведомления',
  greeting: 'Привет, Айгерим',
  encouragement: 'Сегодня тренировка — вы справитесь!',
  soon: 'Скоро тренировка. Панда уже разминается.',
  today: 'Сегодня',
  next: 'Ближайшее занятие',
  confirmed: 'Подтверждено',
  hasTransfer: 'Есть перенос',
  onsite: 'Тренер подберёт упражнения на месте',
  individual: 'Индивидуальная тренировка',
  group: 'Занятие в мини-группе',
  groupSuffix: ' · Мини-группа',
  programPreview: '{{program}} · {{exercises}}{{more}}',
  moreExercises: ' · ещё {{count}}',
  upcomingBooking: '{{date}} · {{start}}',
  upcomingProgram: '{{program}}{{group}}',
  propose: 'Предложить перенос',
  cancel: 'Отменить запись',
  cancelTitle: 'Отменить запись?',
  keep: 'Оставить занятие',
  cancelHint:
    'При отмене тренер отдельно решает вопрос списания. Отмена не создаёт автоматический штраф и не гарантирует, что занятие не будет списано.',
  transfers: 'Переносы других занятий',
  transfer: 'Перенос занятия',
  current: 'Действует',
  proposed: 'Предложено',
  waiting: 'Ждём ответа тренера. До согласия действует прежнее время.',
  withdraw: 'Отозвать запрос',
  balance: 'Остаток пакета',
  package: 'Пакет 12 занятий',
  units: 'из {{count}} занятий',
  due: 'К оплате 40 000 ₸',
  upcoming: 'Следующие занятия',
  history: 'История занятий',
  offline: 'Нет связи. Показаны сохранённые данные.',
  empty: 'Записей нет',
  emptyHint:
    'Согласуйте следующее занятие с тренером. Он добавит время — запись появится здесь.',
  loading: 'Загрузка раздела',
  todayDate: 'пн, 14 сен',
  futureDate: 'чт, 17 сен',
  futureShort: '17 сен',
  proposedDate: '18 сен',
  program: 'Низ А · Приседания со штангой, Румынская тяга, Жим ногами · ещё 2',
  currentTime: '18:00–19:00',
  proposedTime: '19:00–20:00',
  upcomingTime: '17 сен · 18:00',
  timeStart: '{{start}}–',
  bookingSummary: '{{date}}, {{start}}–{{end}}',
};
