import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  root: { flex: 1 },
  body: { paddingBottom: 20 },
  topbar: {
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 18,
    paddingRight: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  trainer: { flexDirection: 'row', alignItems: 'center', gap: 9 },
  avatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#262b45',
  },
  initials: {
    color: '#ffffff',
    fontFamily: 'Inter_800ExtraBold',
    fontSize: 14,
    letterSpacing: 0.3,
  },
  trainerText: { fontSize: 14, lineHeight: 16.8 },
  iconButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  encouragement: {
    paddingTop: 4,
    paddingHorizontal: 18,
    fontSize: 14,
    lineHeight: 20.3,
    fontFamily: 'Inter_700Bold',
  },
  title: {
    paddingTop: 2,
    paddingHorizontal: 18,
    paddingBottom: 12,
    fontFamily: 'Montserrat_800ExtraBold',
    fontSize: 27,
    lineHeight: 28.08,
    letterSpacing: -0.5,
  },
  page: { paddingHorizontal: 16 },
  hero: { padding: 20, borderRadius: 24, overflow: 'hidden' },
  top: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  small: { fontSize: 14, lineHeight: 20.3 },
  date: { marginTop: 20 },
  when: {
    marginTop: 5,
    fontFamily: 'Montserrat_800ExtraBold',
    fontSize: 30,
    lineHeight: 36,
    letterSpacing: -0.6,
  },
  end: { fontFamily: 'Montserrat_600SemiBold' },
  mascot: { position: 'absolute', right: 10, top: 46, width: 92, height: 124 },
  meta: { paddingRight: 84, marginTop: 18, gap: 4 },
  program: { fontFamily: 'Inter_700Bold', fontSize: 16, lineHeight: 24 },
  actions: { marginTop: 20, gap: 4 },
  section: { paddingHorizontal: 16, marginTop: 22 },
  sectionTitle: {
    marginHorizontal: 4,
    marginBottom: 12,
    fontFamily: 'Inter_700Bold',
    fontSize: 16,
    lineHeight: 21.6,
  },
  request: { padding: 16, borderWidth: 1, borderRadius: 18 },
  requestLabel: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  dates: {
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  dateColumn: { flex: 1, gap: 4 },
  waiting: { fontSize: 14, lineHeight: 21 },
  requestAction: { marginTop: 12 },
  packageSection: { paddingHorizontal: 16, paddingTop: 16 },
  package: { padding: 16 },
  packageHeading: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 6,
  },
  value: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 8,
    marginVertical: 12,
  },
  number: {
    fontFamily: 'Montserrat_800ExtraBold',
    fontSize: 30,
    lineHeight: 33,
  },
  meter: { height: 8, borderRadius: 99, overflow: 'hidden' },
  meterFill: { height: 8, borderRadius: 99 },
  due: { marginTop: 12, alignItems: 'flex-start' },
  upcoming: { paddingVertical: 14, paddingHorizontal: 12, marginHorizontal: 6 },
  rowTitle: {
    fontSize: 15.5,
    lineHeight: 22.475,
    letterSpacing: 0.1,
    fontFamily: 'Inter_600SemiBold',
  },
  rowMeta: { marginTop: 2, fontSize: 14, lineHeight: 20.3 },
  history: { paddingHorizontal: 16, paddingTop: 18 },
  notice: {
    marginHorizontal: 16,
    marginBottom: 14,
    paddingVertical: 13,
    paddingHorizontal: 15,
    borderRadius: 18,
    flexDirection: 'row',
    gap: 11,
  },
  noticeText: {
    flex: 1,
    fontSize: 14,
    lineHeight: 21,
    fontFamily: 'Inter_500Medium',
  },
  empty: {
    paddingTop: 8,
    paddingHorizontal: 12,
    paddingBottom: 20,
    alignItems: 'center',
  },
  emptyMascot: { width: 170, height: 170, marginBottom: 14 },
  emptyTitle: {
    marginTop: 14,
    fontFamily: 'Inter_700Bold',
    fontSize: 17,
    lineHeight: 23.8,
    textAlign: 'center',
  },
  emptyHint: {
    marginTop: 6,
    fontSize: 14,
    lineHeight: 21.7,
    textAlign: 'center',
  },
  skeletonRow: {
    paddingVertical: 14,
    paddingHorizontal: 12,
    marginHorizontal: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  skeletonCard: { paddingVertical: 6 },
  skeletonCircle: { width: 42, height: 42, borderRadius: 21 },
  skeletonMain: { flex: 1 },
  skeletonTitle: { width: '60%', height: 14, borderRadius: 10 },
  skeletonMeta: { width: '40%', height: 12, borderRadius: 10, marginTop: 8 },
});
